# Generated by Django 5.0.6 on 2024-06-14 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_uri', models.CharField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('agent_type', models.CharField(choices=[('Organization', 'Organization')])),
                ('point_of_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.agent')),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_parent_organization_set', to='newdb.agent')),
            ],
            options={
                'db_table': 'agent',
                'db_table_comment': 'Merge Person and Organization into single table to make  linking to agents easier. Most roles are hard typed in this model.  Need validation criteria-- \n\t- If agent_type is Person, then organization_affiliation,  fname, lname is allowed, and parent_organization_id should be null \n\t- if agent_type os Organization, then organization_affiliation, fname, lname  should be null and parent_organization_id is allowed. \n- point of contact should be an e-mail address.  If possible, should be a repository role that will outlast the tenure of individuals at the repository.\n- label is the text that will be displayed for the agent in UI.\n- If person name, affiliation, parent organization changes, this should generate a new agent instance; the agent_uri should be constant, allowing aggregation of the various stages of the agent history.',
            },
        ),
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('collection_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'collection_type',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('iso3166code', models.CharField(blank=True, max_length=3, null=True)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='GeologicTimeScale',
            fields=[
                ('geologic_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geologic_time_interval_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('numeric_older_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('numeric_younger_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'geologic_time_scale',
                'db_table_comment': 'vocabulary of ICS geologic time ordinal eras, 2024 version',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InitiativeType',
            fields=[
                ('initiative_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'initiative_type',
            },
        ),
        migrations.CreateModel(
            name='LaunchType',
            fields=[
                ('launch_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'launch_type',
            },
        ),
        migrations.CreateModel(
            name='LocationMethod',
            fields=[
                ('location_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'location_method',
                'db_table_comment': 'was nav_type',
            },
        ),
        migrations.CreateModel(
            name='PlatformType',
            fields=[
                ('platform_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'platform_type',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('property_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'property_type',
                'db_table_comment': 'vocabulary of properties that might have values assigned for a material sample',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('relation_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'relation_type',
                'db_table_comment': 'terms to assign semantics for relations between samples. Relations can detail the relationship between parent and child samples, use to link to publications, data, other online resources, relate to other samples.',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('resource_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'resource_type',
                'db_table_comment': 'kinds of things a sample can be related to, e.g. publication, dataset, sample, research project',
            },
        ),
        migrations.CreateModel(
            name='SamplingMethod',
            fields=[
                ('collection_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('method_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sampling_method',
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
            },
        ),
        migrations.CreateModel(
            name='SesarUser',
            fields=[
                ('sesar_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='newdb.agent')),
                ('sso_account_id', models.IntegerField()),
                ('is_admin', models.BooleanField()),
                ('note', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_permission_status', models.IntegerField(blank=True, null=True)),
                ('upload_permission_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('legacy_user_id', models.IntegerField(blank=True, null=True)),
                ('geopass_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sesar_user',
            },
        ),
        migrations.CreateModel(
            name='GeometryColumns',
            fields=[
                ('f_table_catalog', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('f_table_schema', models.CharField(max_length=256)),
                ('f_table_name', models.CharField(max_length=256)),
                ('f_geometry_column', models.CharField(max_length=256)),
                ('coord_dimension', models.IntegerField()),
                ('srid', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'geometry_columns',
                'unique_together': {('f_table_catalog', 'f_table_schema', 'f_table_name', 'f_geometry_column')},
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(blank=True, null=True)),
                ('group_type', models.ForeignKey(blank=True, db_comment="type of group such as 'award' or 'user defined'", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.collectiontype')),
                ('group_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser')),
            ],
            options={
                'db_table': 'groups',
                'db_table_comment': 'Definition of a group or collection defined by some user to associate a set of samples for some purpose.',
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('initiative_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('funding', models.CharField(blank=True, max_length=50, null=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('initiative_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('initiative_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.initiativetype')),
            ],
            options={
                'db_table': 'initiative',
                'db_table_comment': 'Definition of an activity related to sample collection or stewardship. includes cruises, field programs, funded projects, ',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('locality_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('locality_uri', models.CharField(blank=True, db_comment='use mindat location identifiers?', max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('permit', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('contained_in', models.ForeignKey(blank=True, db_column='contained_in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.locality')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.country')),
            ],
            options={
                'db_table': 'locality',
                'db_table_comment': 'definition of a named place associated with some geologic feature of interest. Binding to concrete geospatial coordinate location is assumed to be through information linked at locality_uri.',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('material_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.materialtype')),
            ],
            options={
                'db_table': 'material_type',
                'db_table_comment': 'was classification',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('host_platform_id', models.IntegerField(blank=True, null=True)),
                ('date_commissioned', models.DateField(blank=True, null=True)),
                ('launch_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.launchtype')),
                ('operator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.agent')),
                ('platform_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.platformtype')),
            ],
            options={
                'db_table': 'platform',
                'db_table_comment': 'Definition of a facility that hosts sampling activities. Typically a ship or ship-based device (e.g. alvin) used to explore marine water bodies in accessible to direct human occupation.  Extent to include extraterrestrial  exploration devices like OSIRIS-REx. ',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(db_comment='primary key for database. ', primary_key=True, serialize=False)),
                ('igsn', models.CharField(db_comment='globally unique identifier string that identifies the material sample. In DataCite/DOI context, this includes the DOI handle, the IGSN prefix and the token assigned when the sample was registered, the toke MUST be unique in the context of the DOI handle and IGSN prefix.', max_length=30)),
                ('igsn_prefix', models.CharField(db_comment='This includes the DOI handle prefix and the IGSN registration authority prefix.  ', max_length=5)),
                ('name', models.CharField(db_comment='name used to represent the sample in user interface; might be IGSN, or a user-defined label for the sample.', max_length=255)),
                ('igsn_is_system_assigned', models.IntegerField(blank=True, null=True)),
                ('is_private', models.IntegerField()),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('archive_date', models.DateTimeField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
                ('size', models.CharField(blank=True, db_comment='text string  specifying size of sample; should be measured value with units of measure. MIght use mass or length dimensions. ', max_length=255, null=True)),
                ('material_name_verbatim', models.CharField(blank=True, db_comment='material name as provided by the original sample collector or sample registrant.', max_length=255, null=True)),
                ('sample_description', models.TextField(blank=True, db_comment='Description of the sample; provide details-- material type, textures, dimensions, why collected, how collected, information about the sample context, etc. ', null=True)),
                ('purpose', models.CharField(blank=True, db_comment='brief explanation of why sample was collected.', max_length=100, null=True)),
                ('geologic_age_verbatim', models.CharField(blank=True, db_comment='geologic age of the sample as reported by the original collector or registrant. ', max_length=500, null=True)),
                ('numeric_age_min', models.DecimalField(blank=True, db_comment='Younger numeric temporal coordinate for age of sample; if only have a single age, provide it here and leave age_max null. \n\nunits are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. ', decimal_places=4, max_digits=9, null=True)),
                ('numeric_age_max', models.DecimalField(blank=True, db_comment='Older numeric temporal coordinate for age range of sample; if only have a single age, provide leave age_max null. \n\nunits are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. ', decimal_places=4, max_digits=9, null=True)),
                ('numeric_age_unit', models.CharField(blank=True, db_comment='units are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. ', max_length=12, null=True)),
                ('geologic_unit', models.CharField(blank=True, db_comment='name of the geologic unit that contains the sample.', max_length=500, null=True)),
                ('age_qualifier', models.CharField(blank=True, db_comment='qualifier to indicate if age assignment is exact, if there are know uncertainty bounds on numeric age, if age is questionable, etc.', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, db_comment='latitude of point location where sample was collected, reported in decimal degrees using WGS84 Spatial reference system. Location coordinates will be rounded to 6 decimal places.  If the sampling location position is specified with other spatial reference system, link through the location table.', decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, db_comment='longitude of point location where sample was collected, reported in decimal degrees using WGS84 Spatial reference system.  Location coordinates will be rounded to 6 decimal places.   If the sampling location position is specified with other spatial reference system, link through the location table.', decimal_places=6, max_digits=9, null=True)),
                ('latitude_end', models.DecimalField(blank=True, db_comment='If the sampling location is a linear feature (e.g. the track of a a dredge haul), report the latitude of the end of the feature, using WGS84 decimal degrees.  ', decimal_places=6, max_digits=8, null=True)),
                ('longitude_end', models.DecimalField(blank=True, db_comment='If the sampling location is a linear feature (e.g. the track of a a dredge haul), report the longitude of the end of the feature, using WGS84 decimal degrees. ', decimal_places=6, max_digits=9, null=True)),
                ('vertical_min', models.DecimalField(blank=True, db_comment='vertical coordinate of sampling location position. Units of measure and the reference system are reported in the linked vertical_reference definition.', decimal_places=4, max_digits=9, null=True)),
                ('vertical_max', models.DecimalField(blank=True, db_comment='if sampling location is a linear feature, e.g. a core from a borehole, report the max  coordinate of the sampling location position. Units of measure and the reference system are reported in the linked vertical_reference definition.  Generally, for cores, max coordinate will be the deepest beneath to datum. ', decimal_places=4, max_digits=9, null=True)),
                ('location_qualifier', models.CharField(blank=True, db_comment='indicate uncertainty, whether locations have be obfuscated intentionally', max_length=50, null=True)),
                ('locality_detail', models.TextField(blank=True, db_comment='linked locality entity has generalized information about the kind of locality; include details specific to this sampling location here. ', null=True)),
                ('collection_method_detail', models.CharField(blank=True, db_comment='text content includes details about specifics of the particular collection event for this sample', max_length=1000, null=True)),
                ('launch_label', models.CharField(blank=True, db_comment='label or identifier for a specify sampling platform deployment from a host platform, e.g launch of Alvin submersible from support ship.', max_length=100, null=True)),
                ('collection_start_date', models.DateTimeField(blank=True, db_comment='date and time of sample acquisition; if the acquisition event is only specfied as a time interval, this is the start of that interval. ', null=True)),
                ('collection_end_date', models.DateTimeField(blank=True, db_comment='If sample acquisition event is specified as a date-time interval, this is the end of that interval. ', null=True)),
                ('collection_date_precision', models.CharField(blank=True, db_comment='indicate time interval that collection time is specified; e.g. minutes, hours, days, weeks, months...', max_length=200, null=True)),
                ('metadata_store_status', models.CharField(db_comment='internal status flag used by SESAR to track metadata management', max_length=25)),
                ('collector', models.ForeignKey(blank=True, db_comment='agent acknowledged for collection of the sample. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_collector_set', to='newdb.agent')),
                ('cruise_field_prgrm', models.ForeignKey(blank=True, db_comment='link to description of the cruise, field program, funded project or other activity that is the context for the collection of this sample', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.initiative')),
                ('cur_owner', models.ForeignKey(blank=True, db_comment='link to current owner of the sample. SESAR uses the owner ID to determine permissions for updating sample records.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_cur_owner_set', to='newdb.agent')),
                ('cur_registrant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_cur_registrant_set', to='newdb.agent')),
                ('current_archive', models.ForeignKey(blank=True, db_comment='link to agent that currently is the steward of the sample.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_current_archive_set', to='newdb.agent')),
                ('general_material_type', models.ForeignKey(blank=True, db_comment='material type from iSamples material type vocabulary. Multiple more specific material types are specified through the sample_material correlation table.  ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.materialtype')),
                ('geologic_age_older', models.ForeignKey(blank=True, db_comment='Link to geologic time interval definition for older age possible for sample. If only have a single interval, leave this field null. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_geologic_age_older_set', to='newdb.geologictimescale')),
                ('geologic_age_younger', models.ForeignKey(blank=True, db_comment='Link to geologic time interval definition for younger age possible for sample. If only have a single interval, provide that here and leave age_olde_id null. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.geologictimescale')),
                ('last_changed_by', models.ForeignKey(blank=True, db_comment='link to agent who most recently changed the content of this record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_last_changed_by_set', to='newdb.agent')),
                ('last_registrant', models.ForeignKey(blank=True, db_comment='link to agent that most recently registered the sample.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_last_registrant_set', to='newdb.agent')),
                ('launch_platform', models.ForeignKey(blank=True, db_comment='If sampling was hosted indirectly from the facility identified, by platform_id, this identifies the proximate sampling device or facility hosted by the platform_id.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_launch_platform_set', to='newdb.platform')),
                ('locality', models.ForeignKey(blank=True, db_comment='link to place name description of sampling location, as opposed to a coordinate position. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.locality')),
                ('location_method_id', models.ForeignKey(blank=True, db_comment='link to description of how the location coordinates have been determined', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.locationmethod')),
                ('org_registrant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.agent')),
                ('orig_owner', models.ForeignKey(blank=True, db_comment='link to agent who was original owner of sample, if different from the current owner.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_orig_owner_set', to='newdb.agent')),
                ('original_archive', models.ForeignKey(blank=True, db_comment='link to first agent that was the steward of the sample, if different from the current steward.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_original_archive_set', to='newdb.agent')),
                ('parent_sample', models.ForeignKey(blank=True, db_comment='This is the sample.sample_id for the parent sample; to get its IGSN would have to do a sample-sample join on origin_sample_id = sample_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('platform', models.ForeignKey(blank=True, db_comment='Identifier for the facility that hosted the sampling event either directly or indirectly. Example of indirect host is launch of remote vehicle from a ship.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.platform')),
                ('req_registrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_req_registrant_set', to='newdb.agent')),
            ],
            options={
                'db_table': 'sample',
                'db_table_comment': 'base table with core sample description fields. The contents of this table are a digital representation of a physical, material sample. ',
            },
        ),
        migrations.CreateModel(
            name='RelatedResource',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_label', models.CharField(max_length=50)),
                ('related_resource_uri', models.CharField(max_length=50)),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.relationtype')),
                ('related_resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.resourcetype')),
                ('sample', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'related_resource',
                'db_table_comment': "table to provide links to web-accessible related resource via their URIs. Can be used to provide more explicit relation between a subsample and its parent that simply 'parent', e.g. mineral_separate, soluble_fraction...",
            },
        ),
        migrations.CreateModel(
            name='OtherProperty',
            fields=[
                ('property_value_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(db_comment='text to display property value in user interface', max_length=50)),
                ('property_value_text', models.CharField(db_comment='property value, serialized as text. the value_data_type is used  to convert to number or treat as URI if appropriated', max_length=256)),
                ('value_data_type', models.CharField(db_comment='data type for property value, if need to cast text as numeric or a URI.', max_length=50)),
                ('provenance', models.CharField(blank=True, db_comment='explanation of how (when, who...) the value was determined', max_length=250, null=True)),
                ('property_type', models.ForeignKey(db_comment='foreign key to property type vocabulary', on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.propertytype')),
                ('sample', models.ForeignKey(db_comment='foreign key to sample table to link property attribution to sample', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'other_property',
                'db_table_comment': 'Optional correlation table to link sample with descriptive properties not explicitly included in this schema. Was sample_customized_metadata',
            },
        ),
        migrations.CreateModel(
            name='GroupSample',
            fields=[
                ('group_sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.groups')),
                ('sample', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'group_sample',
                'db_table_comment': 'correlation table that associated a sample with a group or collection. ',
            },
        ),
        migrations.CreateModel(
            name='SampleAdditionalIdentifier',
            fields=[
                ('sample_external_identifier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier_scheme', models.CharField(max_length=50)),
                ('identifier_value', models.CharField(max_length=256)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'sample_additional_identifier',
                'db_table_comment': 'Simple link to implement one to many relation from sample id to other identifiers assigned to the sample',
            },
        ),
        migrations.CreateModel(
            name='SampleAdditionalName',
            fields=[
                ('additional_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'sample_additional_name',
                'db_table_comment': 'simple table to link one sample to potentially many different other names by which it is known',
            },
        ),
        migrations.CreateModel(
            name='SampledFeatureType',
            fields=[
                ('feature_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_feature_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampledfeaturetype')),
            ],
            options={
                'db_table': 'sampled_feature_type',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sampled_feature_type',
            field=models.ForeignKey(blank=True, db_comment='was primary_location_type. Map to iSamples Sampled feature; this will likely be some geoscience feature. Link to controlled vocabulary.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampledfeaturetype'),
        ),
        migrations.AddField(
            model_name='locality',
            name='feature_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampledfeaturetype'),
        ),
        migrations.CreateModel(
            name='SampleMaterial',
            fields=[
                ('sample_material_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.materialtype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'sample_material',
                'db_table_comment': 'Correlation table to implement many to many relationship between samples and material constituents of the sample.',
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('sample_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_name', models.CharField(blank=True, max_length=50, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_sample_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampletype')),
            ],
            options={
                'db_table': 'sample_type',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(db_comment='corresponds to iSamples material sample type, use iSamples vocabulary with earth science extensions.', on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampletype'),
        ),
        migrations.AddField(
            model_name='sample',
            name='collection_method',
            field=models.ForeignKey(blank=True, db_comment='link to generic description of the collection method', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.samplingmethod'),
        ),
        migrations.AddField(
            model_name='sample',
            name='vertical_reference',
            field=models.ForeignKey(blank=True, db_comment="link to definition of vertical reference system; the definition must specify the units of measure, the datum ('0' surface) and the positive direction for coordinate values (up or down)", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.spatialrefsys'),
        ),
        migrations.CreateModel(
            name='GeospatialLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(db_comment='text to display this location position in user interface. ', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, db_comment='information about the position determination and representation.', null=True)),
                ('vertical', models.DecimalField(blank=True, db_comment='based on vertical_srs, might be elevation (positive up) or depth (positive down).', decimal_places=4, max_digits=10, null=True)),
                ('coordinate_1', models.DecimalField(blank=True, db_comment='coordinate order (what is coordinate_1, coordinate_2) and interpretation must be specified in the spatial_reference_system definition. ', decimal_places=4, max_digits=12, null=True)),
                ('coordinate_2', models.DecimalField(blank=True, db_comment='coordinate order (what is coordinate_1, coordinate_2) and interpretation must be specified in the spatial_reference_system definition. ', decimal_places=4, max_digits=12, null=True)),
                ('wkt_geometry', models.CharField(blank=True, db_column='WKT_geometry', max_length=100, null=True)),
                ('global_grid_cell_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sample', models.ForeignKey(db_comment='link to sample that this position applies to. ', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('spatial_reference_system', models.ForeignKey(blank=True, db_column='spatial_reference_system', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geospatiallocation_spatial_reference_system_set', to='newdb.spatialrefsys')),
                ('vertical_srs', models.ForeignKey(blank=True, db_column='vertical_srs', db_comment='defines units of measure for vertical coordinate, positive up or positive down, and the datum-- that is the surface that has a 0 coordinate value.   If the position is within a borehole, the vertical_srs might be the borehole geometry. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.spatialrefsys')),
            ],
            options={
                'db_table': 'geospatial_location',
                'db_table_comment': 'The latitude and longitude in the sample table are required to use WGS84 decimal degrees. This table is optional, use to report coordinate locations with spatial reference different from WGS84, e.g. UTM, local grid coordinates, global grid cell identifiers, etc. ',
            },
        ),
        migrations.CreateModel(
            name='RelatedLocalDoc',
            fields=[
                ('local_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_image', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('path_to_file', models.CharField(blank=True, max_length=400, null=True)),
                ('uploaded_date', models.DateField(blank=True, null=True)),
                ('sample', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser')),
            ],
            options={
                'db_table': 'related_local_doc',
                'db_table_comment': 'Table to provide links from sample to document hosted in the file system local to the SESAR server',
            },
        ),
    ]
