# Generated by Django 5.0.6 on 2024-06-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('Organization', 'Organization')], max_length=50),
        ),
    ]
