# Generated by Django 5.0.6 on 2024-09-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geospatiallocation',
            name='spatial_reference_system',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='vertical_reference',
        ),
        migrations.RemoveField(
            model_name='geospatiallocation',
            name='vertical_srs',
        ),
        # migrations.DeleteModel(
        #     name='SpatialRefSys',
        # ),
    ]
