# Generated by Django 5.0.6 on 2024-09-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0002_remove_geospatiallocation_spatial_reference_system_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeometryColumns',
        ),
    ]
