# Generated by Django 5.0.6 on 2024-09-04 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0003_delete_geometrycolumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='geospatiallocation',
            name='spatial_reference_system',
            field=models.ForeignKey(blank=True, db_column='spatial_reference_system', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='geospatiallocation_spatial_reference_system_set', to='newdb.spatialrefsys'),
        ),
        migrations.AddField(
            model_name='geospatiallocation',
            name='vertical_srs',
            field=models.ForeignKey(blank=True, db_column='vertical_srs', db_comment='defines units of measure for vertical coordinate, positive up or positive down, and the datum-- that is the surface that has a 0 coordinate value.   If the position is within a borehole, the vertical_srs might be the borehole geometry. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.spatialrefsys'),
        ),
        migrations.AddField(
            model_name='sample',
            name='vertical_reference',
            field=models.ForeignKey(blank=True, db_comment="link to definition of vertical reference system; the definition must specify the units of measure, the datum ('0' surface) and the positive direction for coordinate values (up or down)", null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.spatialrefsys'),
        ),
    ]
