# Generated by Django 5.0.6 on 2024-09-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0004_geospatiallocation_spatial_reference_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geologictimescale',
            name='notation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
