# Generated by Django 5.0.6 on 2024-09-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0005_geologictimescale_notation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='collector',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='last_registrant',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='org_registrant',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='orig_owner',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='original_archive',
        ),
    ]
