# Generated by Django 5.0.6 on 2024-09-05 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newdb', '0006_remove_sample_collector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupsample',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupsample',
            name='sample',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('activate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('doi_prefix', models.CharField(default='10.58052/', max_length=16)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser')),
                ('part_of_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='newdb.group')),
            ],
            options={
                'db_table': 'group',
                'db_table_comment': 'definition imported from SCao migration in legacy db updates',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newdb.group')),
                ('sesar_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser')),
            ],
            options={
                'db_table': 'group_member',
                'db_table_comment': 'Related sesar user to a group. Definition imported from SCao migration in legacy db updates',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='newdb.GroupMember', to='newdb.sesaruser'),
        ),
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(blank=True, null=True)),
                ('collection_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser')),
                ('collection_type', models.ForeignKey(blank=True, db_comment='type of collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.collectiontype')),
            ],
            options={
                'db_table': 'sample_collection',
                'db_table_comment': 'Definition of set of samples by some user to associate a set of samples for some purpose.',
            },
        ),
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('collection_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('collection', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.samplecollection')),
            ],
            options={
                'db_table': 'collection_member',
                'db_table_comment': 'correlation table that associated a sample with a collection. ',
            },
        ),
        # migrations.DeleteModel(
        #     name='Groups',
        # ),
        migrations.DeleteModel(
            name='GroupSample',
        ),
    ]
