version: '3.9'

services:
  sesar-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
      NEXT_PUBLIC_API2_BASE_URL: ${NEXT_PUBLIC_API2_BASE_URL}
    env_file:
      - .env
    restart: unless-stopped
