# Generated by Django 5.0.6 on 2024-06-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesaruser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sesarusercode',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'managed': True},
        ),
    ]
