# Generated by Django 5.0.6 on 2024-07-02 14:46

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0003_sesaruser_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesaruser',
            name='doi_prefix',
            field=models.CharField(default='10.58052/', max_length=10),
        ),
        migrations.AlterField(
            model_name='sesaruser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sesaruser',
            name='is_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sesaruser',
            name='last_login',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='sesaruser',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now(), null=True),
        ),
        migrations.AlterField(
            model_name='sesaruser',
            name='upload_permission_status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
