# Generated by Django 5.0.6 on 2024-07-16 19:54

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sesar_api', '0004_alter_sesaruser_doi_prefix_alter_sesaruser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='auth_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('doi_prefix', models.CharField(default='10.58052/', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser')),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.organization')),
                ('sesar_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser')),
            ],
            options={
                'db_table': 'organization_member',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', through='sesar_api.OrganizationMember', to='sesar_api.sesaruser'),
        ),
        migrations.CreateModel(
            name='OrganizationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('activate_date', models.DateTimeField(default=django.db.models.functions.datetime.Now())),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.organization')),
            ],
            options={
                'db_table': 'organization_team',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='organization_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.organizationteam'),
        ),
        migrations.CreateModel(
            name='OrganizationTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.organizationmember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.organizationteam')),
            ],
            options={
                'db_table': 'organization_team_member',
            },
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='teams',
            field=models.ManyToManyField(related_name='members', through='sesar_api.OrganizationTeamMember', to='sesar_api.organizationteam'),
        ),
    ]
