# Generated by Django 5.0.6 on 2024-07-17 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0005_usercodepermission_auth_group_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesarusercode',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.organization'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='organization_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='sesar_api.organizationteam'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='sesar_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permissions', to='sesar_api.sesaruser'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user_code',
            field=models.ForeignKey(db_column='user_code', max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='sesar_api.sesarusercode', to_field='user_code'),
        ),
    ]
