# Generated by Django 5.0.6 on 2024-07-29 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0007_alter_user_options_samplepermission_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='user_code',
            field=models.ForeignKey(blank=True, db_column='user_code', max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='sesar_api.sesarusercode', to_field='user_code'),
        ),
        migrations.AlterField(
            model_name='sesarusercode',
            name='doi_prefix',
            field=models.CharField(default='10.58052/', max_length=16),
        ),
    ]
