# Generated by Django 5.0.6 on 2024-07-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0008_alter_samplepermission_usercode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'managed': True},
        ),
    ]
