# Generated by Django 5.0.6 on 2024-07-31 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0009_alter_sample_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='organization_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_samples_set', to='sesar_api.organization'),
        ),
    ]
