# Generated by Django 5.0.6 on 2024-08-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0010_sample_organization_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
