# Generated by Django 5.0.6 on 2024-08-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0011_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationteammember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesar_api.organizationmember'),
        ),
        migrations.AlterField(
            model_name='organizationteammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesar_api.organizationteam'),
        ),
    ]
