# Generated by Django 5.0.6 on 2024-08-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0013_alter_organization_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationteam',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='sesar_api.organization'),
        ),
    ]
