# Generated by Django 5.0.6 on 2024-08-26 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0014_alter_organizationteam_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmember',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='sesarusercode',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organizationteam',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='organization_owner',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='sesar_user',
        ),
        migrations.RemoveField(
            model_name='organizationmember',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='organizationteammember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='organizationteammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='organization_team',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('activate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('doi_prefix', models.CharField(default='10.58052/', max_length=16)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser')),
                ('part_of_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sesar_api.group')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='sesar_api.group'),
        ),
        migrations.AddField(
            model_name='sample',
            name='group_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_samples_set', to='sesar_api.group'),
        ),
        migrations.AddField(
            model_name='sesarusercode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.group'),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesar_api.group')),
                ('sesar_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser')),
            ],
            options={
                'db_table': 'group_member',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='sesar_api.GroupMember', to='sesar_api.sesaruser'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
        migrations.DeleteModel(
            name='OrganizationTeamMember',
        ),
        migrations.DeleteModel(
            name='OrganizationTeam',
        ),
    ]
