# Generated by Django 5.0.6 on 2024-08-29 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0015_restructure_organizations_into_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='granted_by_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to='sesar_api.group'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='activate_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
