# Generated by Django 5.0.6 on 2024-09-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0016_permission_granted_by_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='contact_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
