# Generated by Django 5.0.6 on 2024-09-30 00:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0017_group_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('new_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_received', to='sesar_api.group')),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_received', to='sesar_api.sesaruser')),
                ('orig_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_sent', to='sesar_api.group')),
                ('orig_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_sent', to='sesar_api.sesaruser')),
                ('transfer_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_created', to='sesar_api.sesaruser')),
            ],
            options={
                'db_table': 'transfer_history',
                'managed': True,
            },
        ),
    ]
