# Generated by Django 5.0.6 on 2024-10-07 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sesar_api', '0018_transferhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='auth_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        ),
    ]
