# Generated by Django 5.0.6 on 2024-10-13 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0019_remove_groupmember_is_admin_groupmember_auth_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='sesar_api.group'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'part_of_group')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'sesar_user')},
        ),
    ]
