# Generated by Django 5.0.6 on 2024-10-15 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0020_alter_group_name_alter_groupmember_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='igsn_prefix',
            field=models.ForeignKey(db_column='igsn_prefix', on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='sesar_api.sesarusercode', to_field='user_code'),
        ),
        migrations.AlterField(
            model_name='sesarusercode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_codes', to='sesar_api.group'),
        ),
        migrations.AlterField(
            model_name='sesarusercode',
            name='is_available',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sesarusercode',
            name='is_grandfather_code',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sesarusercode',
            name='sesar_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_codes', to='sesar_api.sesaruser'),
        ),
        migrations.AlterField(
            model_name='sesarusercode',
            name='user_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
