# Generated by Django 5.0.6 on 2024-10-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0021_alter_sample_igsn_prefix_alter_sesarusercode_group_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(condition=models.Q(('group_owner__isnull', False)), fields=['group_owner'], name='sample_g_owner_non_null_idx'),
        ),
    ]
