# Generated by Django 5.0.6 on 2025-01-02 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0022_sample_sample_g_owner_non_null_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='igsn_prefix',
            field=models.ForeignKey(blank=True, db_column='igsn_prefix', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='sesar_api.sesarusercode', to_field='user_code'),
        ),
    ]
