# Generated by Django 5.0.6 on 2025-01-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0023_alter_sample_igsn_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='display_name',
            field=models.CharField(default='changeme', max_length=64),
            preserve_default=False,
        ),
    ]
