# Generated by Django 5.0.6 on 2025-01-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0024_group_display_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('part_of_group__isnull', False)), fields=('name', 'part_of_group'), name='unique_name_group'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('part_of_group__isnull', True)), fields=('name',), name='unique_name_when_no_group'),
        ),
    ]
