# Generated by Django 5.0.6 on 2025-02-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0025_alter_group_unique_together_group_unique_name_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='contact_email',
            field=models.EmailField(max_length=255),
        ),
    ]
