# Generated by Django 5.0.6 on 2025-02-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0026_alter_group_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
