# Generated by Django 5.0.6 on 2025-02-24 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sesar_api', '0027_groupmember_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="part_of_group",
            new_name="part_of_team",
        ),

        migrations.RenameField(
            model_name="permission",
            old_name="group",
            new_name="team",
        ),

        migrations.RenameField(
            model_name="permission",
            old_name="granted_by_group",
            new_name="granted_by_team",
        ),

        migrations.RenameField(
            model_name="sample",
            old_name="group_owner",
            new_name="team_owner",
        ),

        migrations.RenameField(
            model_name="sesarusercode",
            old_name="group",
            new_name="team",
        ),

        migrations.RenameField(
            model_name="transferhistory",
            old_name="orig_group",
            new_name="orig_team",
        ),

        migrations.RenameField(
            model_name="transferhistory",
            old_name="new_group",
            new_name="new_team",
        ),

        migrations.RenameField(
            model_name="groupmember",
            old_name="group",
            new_name="team",
        ),

        migrations.RenameModel(
            old_name='Group',
            new_name='Team',
        ),

        migrations.RenameModel(
            old_name='GroupMember',
            new_name='TeamMember',
        ),

        # Rename "group" table to "team"
        migrations.RunSQL(
            "ALTER TABLE \"group\" RENAME TO team;",
            reverse_sql="ALTER TABLE team RENAME TO \"group\";",
        ),

        # Rename "group_member" table to "team_member"
        migrations.RunSQL(
            "ALTER TABLE group_member RENAME TO team_member;",
            reverse_sql="ALTER TABLE team_member RENAME TO group_member;",
        ),

        # Rename unique constraints (implemented as indexes in postgres)
        migrations.RunSQL(
            "ALTER INDEX unique_name_group RENAME TO unique_name_team;",
            reverse_sql="ALTER INDEX unique_name_team RENAME TO unique_name_group;",
        ),

        migrations.RunSQL(
            "ALTER INDEX unique_name_when_no_group RENAME TO unique_name_when_no_team;",
            reverse_sql="ALTER INDEX unique_name_when_no_team RENAME TO unique_name_when_no_group;",
        ),

        # Rename index
        migrations.RunSQL(
            "ALTER INDEX sample_g_owner_non_null_idx RENAME TO sample_t_owner_non_null_idx;",
            reverse_sql="ALTER INDEX sample_t_owner_non_null_idx RENAME TO sample_g_owner_non_null_idx;",
        ),

        # Update Django model references
        migrations.AlterModelOptions(
            name='team',
            options={'db_table': 'team'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'db_table': 'team_member'},
        ),

        # Update fields in Django models
        migrations.AlterField(
            model_name='team',
            name='part_of_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='sesar_api.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sesar_api.team'),
        ),

        # Ensure relationships are preserved
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'sesar_user')},
        )
    ]
