# Generated by Django 5.0.6 on 2025-02-24 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sesar_api', '0027_groupmember_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="part_of_group",
            new_name="part_of_team",
        ),

        migrations.RenameField(
            model_name="permission",
            old_name="group",
            new_name="team",
        ),

        migrations.RenameField(
            model_name="permission",
            old_name="granted_by_group",
            new_name="granted_by_team",
        ),

        migrations.RenameField(
            model_name="sample",
            old_name="group_owner",
            new_name="team_owner",
        ),

        migrations.RenameField(
            model_name="sesarusercode",
            old_name="group",
            new_name="team",
        ),

        migrations.RenameField(
            model_name="transferhistory",
            old_name="orig_group",
            new_name="orig_team",
        ),

        migrations.RenameField(
            model_name="transferhistory",
            old_name="new_group",
            new_name="new_team",
        ),

        migrations.RenameField(
            model_name="groupmember",
            old_name="group",
            new_name="team",
        ),

        migrations.RenameModel(
            old_name='Group',
            new_name='Team',
        ),

        migrations.RenameModel(
            old_name='GroupMember',
            new_name='TeamMember',
        ),

        # Rename "group" table to "team"
        migrations.RunSQL(
            "ALTER TABLE \"group\" RENAME TO team;",
            reverse_sql="ALTER TABLE team RENAME TO \"group\";",
        ),

        # Rename "group_member" table to "team_member"
        migrations.RunSQL(
            "ALTER TABLE group_member RENAME TO team_member;",
            reverse_sql="ALTER TABLE team_member RENAME TO group_member;",
        ),

        # Rename foreign key columns in other tables
        # migrations.RunSQL(
        #     "ALTER TABLE permission RENAME COLUMN group_id TO team_id;",
        #     reverse_sql="ALTER TABLE permission RENAME COLUMN team_id TO group_id;",
        # ),
        # migrations.RunSQL(
        #     "ALTER TABLE sample RENAME COLUMN group_owner_id TO team_owner_id;",
        #     reverse_sql="ALTER TABLE sample RENAME COLUMN team_owner_id TO group_owner_id;",
        # ),
        # migrations.RunSQL(
        #     "ALTER TABLE sesar_user_code RENAME COLUMN group_id TO team_id;",
        #     reverse_sql="ALTER TABLE sesar_user_code RENAME COLUMN team_id TO group_id;",
        # ),
        # migrations.RunSQL(
        #     "ALTER TABLE transfer_history RENAME COLUMN orig_group_id TO orig_team_id;",
        #     reverse_sql="ALTER TABLE transfer_history RENAME COLUMN orig_team_id TO orig_group_id;",
        # ),
        # migrations.RunSQL(
        #     "ALTER TABLE transfer_history RENAME COLUMN new_group_id TO new_team_id;",
        #     reverse_sql="ALTER TABLE transfer_history RENAME COLUMN new_team_id TO new_group_id;",
        # ),
        # migrations.RunSQL(
        #     "ALTER TABLE permission RENAME COLUMN granted_by_group_id TO granted_by_team_id;",
        #     reverse_sql="ALTER TABLE permission RENAME COLUMN granted_by_team_id TO granted_by_group_id;",
        # ),

        # Rename unique constraints (implemented as indexes in postgres)
        migrations.RunSQL(
            "ALTER INDEX unique_name_group RENAME TO unique_name_team;",
            reverse_sql="ALTER INDEX unique_name_team RENAME TO unique_name_group;",
        ),

        migrations.RunSQL(
            "ALTER INDEX unique_name_when_no_group RENAME TO unique_name_when_no_team;",
            reverse_sql="ALTER INDEX unique_name_when_no_team RENAME TO unique_name_when_no_group;",
        ),

        # Rename index
        migrations.RunSQL(
            "ALTER INDEX sample_g_owner_non_null_idx RENAME TO sample_t_owner_non_null_idx;",
            reverse_sql="ALTER INDEX sample_t_owner_non_null_idx RENAME TO sample_g_owner_non_null_idx;",
        ),

        # Update Django model references
        migrations.AlterModelOptions(
            name='team',
            options={'db_table': 'team'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'db_table': 'team_member'},
        ),

        # Update fields in Django models
        migrations.AlterField(
            model_name='team',
            name='part_of_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='sesar_api.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sesar_api.team'),
        ),

        # Ensure relationships are preserved
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'sesar_user')},
        ),


        # migrations.CreateModel(
        #     name='Team',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=64)),
        #         ('display_name', models.CharField(max_length=64)),
        #         ('description', models.CharField(blank=True, max_length=255, null=True)),
        #         ('contact_email', models.EmailField(max_length=255)),
        #         ('activate_date', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('deactivate_date', models.DateTimeField(blank=True, null=True)),
        #         ('doi_prefix', models.CharField(default='10.58052/', max_length=16)),
        #     ],
        #     options={
        #         'db_table': 'team',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='TeamMember',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('status', models.CharField(blank=True, max_length=32, null=True)),
        #     ],
        #     options={
        #         'db_table': 'team_member',
        #     },
        # ),
        # migrations.RemoveField(
        #     model_name='group',
        #     name='members',
        # ),
        # migrations.RemoveField(
        #     model_name='group',
        #     name='owner',
        # ),
        # migrations.RemoveField(
        #     model_name='group',
        #     name='part_of_group',
        # ),
        # migrations.RemoveField(
        #     model_name='sample',
        #     name='group_owner',
        # ),
        # migrations.RemoveField(
        #     model_name='sesarusercode',
        #     name='group',
        # ),
        # migrations.RemoveField(
        #     model_name='transferhistory',
        #     name='orig_group',
        # ),
        # migrations.RemoveField(
        #     model_name='permission',
        #     name='granted_by_group',
        # ),
        # migrations.RemoveField(
        #     model_name='permission',
        #     name='group',
        # ),
        # migrations.RemoveField(
        #     model_name='transferhistory',
        #     name='new_group',
        # ),
        # migrations.RemoveField(
        #     model_name='groupmember',
        #     name='group',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='groupmember',
        #     unique_together=None,
        # ),
        # migrations.RemoveField(
        #     model_name='groupmember',
        #     name='auth_group',
        # ),
        # migrations.RemoveField(
        #     model_name='groupmember',
        #     name='sesar_user',
        # ),
        # migrations.RemoveIndex(
        #     model_name='sample',
        #     name='sample_g_owner_non_null_idx',
        # ),
        # migrations.AddField(
        #     model_name='team',
        #     name='owner',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser'),
        # ),
        # migrations.AddField(
        #     model_name='team',
        #     name='part_of_team',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subteams', to='sesar_api.team'),
        # ),
        # migrations.AddField(
        #     model_name='permission',
        #     name='granted_by_team',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to='sesar_api.team'),
        # ),
        # migrations.AddField(
        #     model_name='permission',
        #     name='team',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='sesar_api.team'),
        # ),
        # migrations.AddField(
        #     model_name='sample',
        #     name='team_owner',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_samples_set', to='sesar_api.team'),
        # ),
        # migrations.AddField(
        #     model_name='sesarusercode',
        #     name='team',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_codes', to='sesar_api.team'),
        # ),
        # migrations.AddField(
        #     model_name='transferhistory',
        #     name='new_team',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_received', to='sesar_api.team'),
        # ),
        # migrations.AddField(
        #     model_name='transferhistory',
        #     name='orig_team',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_sent', to='sesar_api.team'),
        # ),
        # migrations.AddIndex(
        #     model_name='sample',
        #     index=models.Index(condition=models.Q(('team_owner__isnull', False)), fields=['team_owner'], name='sample_t_owner_non_null_idx'),
        # ),
        # migrations.AddField(
        #     model_name='teammember',
        #     name='auth_group',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group'),
        # ),
        # migrations.AddField(
        #     model_name='teammember',
        #     name='sesar_user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser'),
        # ),
        # migrations.AddField(
        #     model_name='teammember',
        #     name='team',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='sesar_api.team'),
        # ),
        # migrations.AddField(
        #     model_name='team',
        #     name='members',
        #     field=models.ManyToManyField(related_name='teams', through='sesar_api.TeamMember', to='sesar_api.sesaruser'),
        # ),
        # migrations.DeleteModel(
        #     name='Group',
        # ),
        # migrations.DeleteModel(
        #     name='GroupMember',
        # ),
        # migrations.AlterUniqueTogether(
        #     name='teammember',
        #     unique_together={('team', 'sesar_user')},
        # ),
        # migrations.AddConstraint(
        #     model_name='team',
        #     constraint=models.UniqueConstraint(condition=models.Q(('part_of_team__isnull', False)), fields=('name', 'part_of_team'), name='unique_name_team'),
        # ),
        # migrations.AddConstraint(
        #     model_name='team',
        #     constraint=models.UniqueConstraint(condition=models.Q(('part_of_team__isnull', True)), fields=('name',), name='unique_name_when_no_team'),
        # ),
    ]
