# Generated by Django 5.0.6 on 2025-02-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0028_rename_user_group_to_team_drop_tables'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SesarUserCode',
            new_name='SesarCode',
        ),
    ]
