# Generated by Django 5.0.6 on 2025-02-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0029_rename_sesarusercode_sesarcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sesarcode',
            table='sesar_code',
        ),
    ]
