# Generated by Django 5.0.6 on 2025-02-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0030_alter_sesarcode_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesarcode',
            old_name='user_code',
            new_name='sesar_code',
        ),
    ]
