# Generated by Django 5.0.6 on 2025-02-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0031_rename_user_code_sesarcode_sesar_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='user_code',
            new_name='sesar_code',
        ),
        migrations.AlterField(
            model_name='sesarcode',
            name='sesar_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sesar_codes', to='sesar_api.sesaruser'),
        ),
        migrations.AlterField(
            model_name='sesarcode',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sesar_codes', to='sesar_api.team'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('geopass_id', 'sesar_code')},
        ),
    ]
