# Generated by Django 5.0.6 on 2025-02-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0032_rename_user_code_permission_sesar_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='sesar_code',
            field=models.ForeignKey(blank=True, db_column='sesar_code', max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='sesar_api.sesarcode', to_field='sesar_code'),
        ),
    ]
