"""
Convert SESAR PostgreSQL data to Parquet format with object references.

Each row represents one object (MaterialSampleRecord, Agent, SamplingEvent, etc.)
with references between rows using integer row_id values.
Code generated by Claude-Code, based on models.py from SESAR2 django, and parquet fields
 based on iSamples JSON schema.
SMR 2025-12-11
"""
import time
import os
import sys
import psycopg2
from psycopg2.extras import RealDictCursor
import duckdb
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from datetime import datetime
import logging
import pathlib

def configure_logger(
        name='sesar2parquet',
        level=logging.INFO,
        log_file="sesarparquet.log"
) -> logging.Logger:
    # Clear any existing handlers
    for handler in logging.root.handlers[:]:
        logging.root.removeHandler(handler)

    handlers = [
        logging.FileHandler(log_file, mode="w"),  # Optional file logging
        logging.StreamHandler(sys.stdout)  # Explicitly log to stdout for ECS
    ]

    logging.basicConfig(
        level=level,
        format='%(asctime)s - %(levelname)s - %(name)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S',
        handlers=handlers
    )

    logger = logging.getLogger(name)
    logger.setLevel(level)
    return logger

# Initialize the default logger
logger = configure_logger()

@dataclass
class DatabaseConfig:
    """Database connection configuration."""
    pg_database: str = os.environ.get('DB_2024_NAME')
    pg_user: str = os.environ.get('DB_2024_USER')
    pg_password: str = os.environ.get('DB_2024_PASSWORD')
    pg_host: str = os.environ.get('DB_2024_HOST')
    pg_port: int = os.environ.get('DB_2024_PORT')
    
    duck_database: str = "sesar_samples.ddb"
    output_parquet: str = "sesar_samples.parquet"


class ObjectRegistry:
    """Registry to track objects and assign unique row IDs."""
    
    def __init__(self):
        self.objects: Dict[str, Dict[str, int]] = {}  # {otype: {object_key: row_id}}
        self.next_id = 1
    
    def register(self, otype: str, key: str) -> int:
        """Register an object and get its row_id."""
        if otype not in self.objects:
            self.objects[otype] = {}
        
        if key not in self.objects[otype]:
            self.objects[otype][key] = self.next_id
            self.next_id += 1
        
        return self.objects[otype][key]
    
    def get_id(self, otype: str, key: str) -> Optional[int]:
        """Get row_id for an existing object."""
        return self.objects.get(otype, {}).get(key)


class SESARToParquetConverter:
    """Convert SESAR data to Parquet format."""
    
    def __init__(self, config: DatabaseConfig):
        self.config = config
        self.pg_conn = None
        self.duck_conn = None
        self.registry = ObjectRegistry()
        self.rows: List[Dict[str, Any]] = []
    
    def connect_postgres(self):
        """Connect to PostgreSQL."""
        self.pg_conn = psycopg2.connect(
            database=self.config.pg_database,
            user=self.config.pg_user,
            password=self.config.pg_password,
            host=self.config.pg_host,
            port=self.config.pg_port,
        )
        logger.info("Connected to PostgreSQL")
    
    def connect_duckdb(self):
        """Connect to DuckDB."""
        self.duck_conn = duckdb.connect(self.config.duck_database)
        logger.info("Connected to DuckDB")
        self._create_schema()
    
    def _create_schema(self):
        """Create DuckDB table schema."""
        schema_sql = """
        CREATE TABLE IF NOT EXISTS samples (
            row_id INTEGER PRIMARY KEY,
            otype VARCHAR,
            
            -- Agent fields
            "Agent.affiliation" VARCHAR,
            "Agent.contact_information" VARCHAR,
            "Agent.identifier" VARCHAR,
            "Agent.name" VARCHAR,
            "Agent.role" VARCHAR,
            
            -- GeospatialCoordLocation fields
            "GeospatialCoordLocation.elevation" VARCHAR,
            "GeospatialCoordLocation.latitude" DECIMAL(10,8),
            "GeospatialCoordLocation.longitude" DECIMAL(11,8),
            "GeospatialCoordLocation.obfuscated" BOOLEAN,
            
            -- IdentifiedConcept fields
            "IdentifiedConcept.identifier" VARCHAR,
            "IdentifiedConcept.label" VARCHAR,
            "IdentifiedConcept.scheme_name" VARCHAR,
            "IdentifiedConcept.scheme_uri" VARCHAR,
            
            -- MaterialSampleCuration fields
            "MaterialSampleCuration.access_constraints" VARCHAR[],
            "MaterialSampleCuration.curation_location" VARCHAR,
            "MaterialSampleCuration.description" VARCHAR,
            "MaterialSampleCuration.label" VARCHAR,
            "MaterialSampleCuration.responsibility" INTEGER[],
            
            -- MaterialSampleRecord fields
            "MaterialSampleRecord.alternate_identifiers" VARCHAR[],
            "MaterialSampleRecord.complies_with" VARCHAR[],
            "MaterialSampleRecord.curation" INTEGER[],
            "MaterialSampleRecord.description" VARCHAR,
            "MaterialSampleRecord.has_context_category" INTEGER[],
            "MaterialSampleRecord.has_material_category" INTEGER[],
            "MaterialSampleRecord.has_sample_object_type" INTEGER[],
            "MaterialSampleRecord.keywords" INTEGER[],
            "MaterialSampleRecord.label" VARCHAR,
            "MaterialSampleRecord.last_modified_time" VARCHAR,
            "MaterialSampleRecord.produced_by" INTEGER[],
            "MaterialSampleRecord.registrant" INTEGER[],
            "MaterialSampleRecord.related_resource" INTEGER[],
            "MaterialSampleRecord.sample_identifier" VARCHAR,
            "MaterialSampleRecord.sampling_purpose" VARCHAR,
            "MaterialSampleRecord.schema" VARCHAR,
            
            -- SampleRelation fields
            "SampleRelation.description" VARCHAR,
            "SampleRelation.label" VARCHAR,
            "SampleRelation.relationship" VARCHAR,
            "SampleRelation.target" VARCHAR,
            
            -- SamplingEvent fields
            "SamplingEvent.authorized_by" VARCHAR[],
            "SamplingEvent.description" VARCHAR,
            "SamplingEvent.has_feature_of_interest" VARCHAR,
            "SamplingEvent.identifier" VARCHAR,
            "SamplingEvent.label" VARCHAR,
            "SamplingEvent.project" VARCHAR,
            "SamplingEvent.responsibility" INTEGER[],
            "SamplingEvent.result_time" VARCHAR,
            "SamplingEvent.geo_location" INTEGER[],
            "SamplingEvent.sampling_site" INTEGER[],
            
            -- SamplingSite fields
            "SamplingSite.description" VARCHAR,
            "SamplingSite.label" VARCHAR,
            "SamplingSite.place_name" VARCHAR[]
        )
        """
        self.duck_conn.execute(schema_sql)
        logger.info("Created DuckDB schema")
    
    def get_blank_row(self) -> Dict[str, Any]:
        """Get a blank row with all columns set to None."""
        return {
            'row_id': None,
            'otype': None,
            'Agent.affiliation': None,
            'Agent.contact_information': None,
            'Agent.identifier': None,
            'Agent.name': None,
            'Agent.role': None,
            'GeospatialCoordLocation.elevation': None,
            'GeospatialCoordLocation.latitude': None,
            'GeospatialCoordLocation.longitude': None,
            'GeospatialCoordLocation.obfuscated': None,
            'IdentifiedConcept.identifier': None,
            'IdentifiedConcept.label': None,
            'IdentifiedConcept.scheme_name': None,
            'IdentifiedConcept.scheme_uri': None,
            'MaterialSampleCuration.access_constraints': None,
            'MaterialSampleCuration.curation_location': None,
            'MaterialSampleCuration.description': None,
            'MaterialSampleCuration.label': None,
            'MaterialSampleCuration.responsibility': None,
            'MaterialSampleRecord.alternate_identifiers': None,
            'MaterialSampleRecord.complies_with': None,
            'MaterialSampleRecord.curation': None,
            'MaterialSampleRecord.description': None,
            'MaterialSampleRecord.has_context_category': None,
            'MaterialSampleRecord.has_material_category': None,
            'MaterialSampleRecord.has_sample_object_type': None,
            'MaterialSampleRecord.keywords': None,
            'MaterialSampleRecord.label': None,
            'MaterialSampleRecord.last_modified_time': None,
            'MaterialSampleRecord.produced_by': None,
            'MaterialSampleRecord.registrant': None,
            'MaterialSampleRecord.related_resource': None,
            'MaterialSampleRecord.sample_identifier': None,
            'MaterialSampleRecord.sampling_purpose': None,
            'MaterialSampleRecord.schema': None,
            'SampleRelation.description': None,
            'SampleRelation.label': None,
            'SampleRelation.relationship': None,
            'SampleRelation.target': None,
            'SamplingEvent.authorized_by': None,
            'SamplingEvent.description': None,
            'SamplingEvent.has_feature_of_interest': None,
            'SamplingEvent.identifier': None,
            'SamplingEvent.label': None,
            'SamplingEvent.project': None,
            'SamplingEvent.responsibility': None,
            'SamplingEvent.result_time': None,
            'SamplingEvent.geo_location': None,
            'SamplingEvent.sampling_site': None,
            'SamplingSite.description': None,
            'SamplingSite.label': None,
            'SamplingSite.place_name': None,
        }
    
    def execute_pg_query(self, query: str, params: tuple = None) -> List[Dict]:
        """Execute PostgreSQL query and return results."""
        with self.pg_conn.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, params)
            return cursor.fetchall()
    
    def execute_pg_query_one(self, query: str, params: tuple = None) -> Optional[Dict]:
        """Execute PostgreSQL query and return single result."""
        with self.pg_conn.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, params)
            result = cursor.fetchone()
            return dict(result) if result else None
    
    def format_iso8601(self, date_value) -> Optional[str]:
        """Convert date to ISO8601 format."""
        if not date_value:
            return None
        
        try:
            if isinstance(date_value, datetime):
                return date_value.isoformat()
            if isinstance(date_value, str):
                dt = datetime.fromisoformat(date_value)
                return dt.isoformat()
            return str(date_value).replace(' ', 'T', 1)
        except Exception:
            return str(date_value).replace(' ', 'T', 1) if date_value else None
    
    # ========================================================================
    # Object Creation Methods
    # ========================================================================
    
    def create_agent(self, agent_type: str, agent_id: int, role: str = '') -> Optional[int]:
        """Create an Agent object and return its row_id."""
        key = f"{agent_type}:{agent_id}"
        
        # Check if already created
        existing_id = self.registry.get_id('Agent', key)
        if existing_id:
            return existing_id
        
        # Get agent data
        if agent_type == 'individual':
            query = "SELECT * FROM individual WHERE individual_id = %s"
        elif agent_type == 'institution':
            query = "SELECT * FROM institution WHERE institution_id = %s"
        else:
            return None
        
        agent_data = self.execute_pg_query_one(query, (agent_id,))
        if not agent_data:
            return None
        
        # Register and create row
        row_id = self.registry.register('Agent', key)
        
        row = self.get_blank_row()
        row['row_id'] = row_id
        row['otype'] = 'Agent'
        
        # Determine name
        if agent_type == 'individual':
            name = (agent_data.get('label') or agent_data.get('individual_uri') or 
                   agent_data.get('description') or agent_data.get('email'))
            identifier = agent_data.get('individual_uri')
        else:  # institution
            name = (agent_data.get('label') or agent_data.get('description') or 
                   agent_data.get('email'))
            identifier = None
        
        # Build contact info
        contact_parts = []
        if agent_data.get('address'):
            contact_parts.append(f"postal: {agent_data['address']}")
        if agent_data.get('email'):
            contact_parts.append(f"email: {agent_data['email']}")
        if agent_data.get('phone'):
            contact_parts.append(f"Phone: {agent_data['phone']}")
        
        row['Agent.name'] = name
        row['Agent.identifier'] = identifier
        row['Agent.contact_information'] = ', '.join(contact_parts) if contact_parts else None
        row['Agent.role'] = role
        row['Agent.affiliation'] = None
        
        self.rows.append(row)
        return row_id
    
    def create_concept(self, concept_type: str, concept_id: int, 
                      label: str, scheme_name: str, scheme_uri: str = None,
                      identifier: str = None) -> int:
        """Create an IdentifiedConcept object and return its row_id."""
        key = f"{concept_type}:{concept_id}"
        
        # Check if already created
        existing_id = self.registry.get_id('IdentifiedConcept', key)
        if existing_id:
            return existing_id
        
        # Register and create row
        row_id = self.registry.register('IdentifiedConcept', key)
        
        row = self.get_blank_row()
        row['row_id'] = row_id
        row['otype'] = 'IdentifiedConcept'
        row['IdentifiedConcept.label'] = label
        row['IdentifiedConcept.scheme_name'] = scheme_name
        row['IdentifiedConcept.scheme_uri'] = scheme_uri
        row['IdentifiedConcept.identifier'] = identifier
        
        self.rows.append(row)
        return row_id
    
    def create_geospatial_location(self, sample_id: int, sample_data: Dict) -> Optional[int]:
        """Create GeospatialCoordLocation and return its row_id."""
        lat = sample_data.get('latitude')
        lon = sample_data.get('longitude')
        
        if not lat and not lon:
            return None
        
        key = f"sample:{sample_id}"
        
        # Check if already created
        existing_id = self.registry.get_id('GeospatialCoordLocation', key)
        if existing_id:
            return existing_id
        
        # Build elevation string
        elev_parts = []
        if sample_data.get('elevation'):
            elev_parts.append(str(sample_data['elevation']))
            if sample_data.get('elevation_uom'):
                elev_parts.append(f"UOM: {sample_data['elevation_uom']}")
        
        depth_min = sample_data.get('depth_min')
        depth_max = sample_data.get('depth_max')
        
        if depth_min or depth_max:
            if depth_min == depth_max:
                elev_parts.append(f"Depth: {depth_min}")
            elif depth_min and depth_max:
                elev_parts.append(f"Depth range: {depth_min} to {depth_max}")
            elif depth_min:
                elev_parts.append(f"Depth minimum: {depth_min}")
            elif depth_max:
                elev_parts.append(f"Depth maximum: {depth_max}")
            
            if sample_data.get('depth_uom'):
                elev_parts.append(f"UOM: {sample_data['depth_uom']}")
        
        elevation = ' '.join(elev_parts) if elev_parts else None
        
        # Register and create row
        row_id = self.registry.register('GeospatialCoordLocation', key)
        
        row = self.get_blank_row()
        row['row_id'] = row_id
        row['otype'] = 'GeospatialCoordLocation'
        row['GeospatialCoordLocation.latitude'] = float(lat) if lat else None
        row['GeospatialCoordLocation.longitude'] = float(lon) if lon else None
        row['GeospatialCoordLocation.elevation'] = elevation
        row['GeospatialCoordLocation.obfuscated'] = False
        
        self.rows.append(row)
        return row_id
    
    def create_sampling_site(self, sample_id: int, sample_data: Dict) -> Optional[int]:
        """Create SamplingSite and return its row_id."""
        key = f"sample:{sample_id}"
        
        # Check if already created
        existing_id = self.registry.get_id('SamplingSite', key)
        if existing_id:
            return existing_id
        
        # Build description
        desc_parts = []
        if sample_data.get('locality_detail'):
            desc_parts.append(sample_data['locality_detail'])
        if sample_data.get('location_qualifier'):
            desc_parts.append(sample_data['location_qualifier'])
        
        description = '; '.join(desc_parts) if desc_parts else None
        
        # Get place names
        place_names = []
        locality_name = sample_data.get('locality_name')
        if locality_name:
            place_names.append(locality_name)
        
        # Register and create row
        row_id = self.registry.register('SamplingSite', key)
        
        row = self.get_blank_row()
        row['row_id'] = row_id
        row['otype'] = 'SamplingSite'
        row['SamplingSite.label'] = locality_name
        row['SamplingSite.description'] = description
        row['SamplingSite.place_name'] = place_names if place_names else None
        
        self.rows.append(row)
        return row_id
    
    def create_sampling_event(self, sample_id: int, sample_data: Dict) -> Optional[int]:
        """Create SamplingEvent and return its row_id."""
        key = f"sample:{sample_id}"
        
        # Check if already created
        existing_id = self.registry.get_id('SamplingEvent', key)
        if existing_id:
            return existing_id
        
        # Build collection description
        desc_parts = []
        if sample_data.get('collection_method_label'):
            desc_parts.append(f"method:{sample_data['collection_method_label']}")
        if sample_data.get('collection_method_detail'):
            desc_parts.append(sample_data['collection_method_detail'])
        if sample_data.get('platform_label'):
            desc_parts.append(f"Platform: {sample_data['platform_label']}")
        if sample_data.get('launch_platform_label'):
            desc_parts.append(f"Launch Platform: {sample_data['launch_platform_label']}")
        if sample_data.get('launch_label'):
            desc_parts.append(f"Launch: {sample_data['launch_label']}")
        
        description = '; '.join(desc_parts) if desc_parts else None
        
        # Get collectors (responsibility)
        query = """
            SELECT individual_id, institution_id, agent_type
            FROM related_sample_agent
            WHERE sample_id = %s AND relation_type_id = 1
        """
        collectors = self.execute_pg_query(query, (sample_id,))
        
        responsibility_ids = []
        for collector in collectors:
            if collector['agent_type'] == 'Individual' and collector.get('individual_id'):
                agent_id = self.create_agent('individual', collector['individual_id'], 'collector')
                if agent_id:
                    responsibility_ids.append(agent_id)
            elif collector['agent_type'] == 'Institution' and collector.get('institution_id'):
                agent_id = self.create_agent('institution', collector['institution_id'], 'collector')
                if agent_id:
                    responsibility_ids.append(agent_id)
        
        # Build result time
        result_time = None
        if sample_data.get('collection_start_date'):
            result_time = self.format_iso8601(sample_data['collection_start_date'])
        elif sample_data.get('collection_end_date'):
            result_time = self.format_iso8601(sample_data['collection_end_date'])
        
        # Build label
        label_parts = []
        if sample_data.get('cruise_field_prgrm_label'):
            label_parts.append(sample_data['cruise_field_prgrm_label'])
        if sample_data.get('launch_label'):
            label_parts.append(sample_data['launch_label'])
        elif sample_data.get('name'):
            label_parts.append(f"Collection of sample {sample_data['name']}")
        
        label = '; '.join(label_parts) if label_parts else 'Sampling event'
        
        # Create geospatial location
        geo_location_id = self.create_geospatial_location(sample_id, sample_data)
        
        # Create sampling site
        sampling_site_id = self.create_sampling_site(sample_id, sample_data)
        
        # Register and create row
        row_id = self.registry.register('SamplingEvent', key)
        
        row = self.get_blank_row()
        row['row_id'] = row_id
        row['otype'] = 'SamplingEvent'
        row['SamplingEvent.label'] = label
        row['SamplingEvent.description'] = description
        row['SamplingEvent.has_feature_of_interest'] = sample_data.get('locality_feature_type')
        row['SamplingEvent.project'] = sample_data.get('cruise_field_prgrm_label')
        row['SamplingEvent.result_time'] = result_time
        row['SamplingEvent.responsibility'] = responsibility_ids if responsibility_ids else None
        row['SamplingEvent.geo_location'] = [geo_location_id] if geo_location_id else None
        row['SamplingEvent.sampling_site'] = [sampling_site_id] if sampling_site_id else None
        
        self.rows.append(row)
        return row_id
    
    def create_curation(self, sample_id: int, sample_data: Dict) -> Optional[int]:
        """Create MaterialSampleCuration and return its row_id."""
        if not sample_data.get('cur_owner_individual_id') and not sample_data.get('cur_owner_institution_id'):
            return None
        
        key = f"sample:{sample_id}"
        
        # Check if already created
        existing_id = self.registry.get_id('MaterialSampleCuration', key)
        if existing_id:
            return existing_id
        
        # Create owner agent
        owner_id = None
        if sample_data.get('cur_owner_individual_id'):
            owner_id = self.create_agent('individual', sample_data['cur_owner_individual_id'], 'owner')
        elif sample_data.get('cur_owner_institution_id'):
            owner_id = self.create_agent('institution', sample_data['cur_owner_institution_id'], 'owner')
        
        if not owner_id:
            return None
        
        # Register and create row
        row_id = self.registry.register('MaterialSampleCuration', key)
        
        row = self.get_blank_row()
        row['row_id'] = row_id
        row['otype'] = 'MaterialSampleCuration'
        row['MaterialSampleCuration.label'] = 'Current curation'
        row['MaterialSampleCuration.description'] = 'current owner'
        row['MaterialSampleCuration.responsibility'] = [owner_id]
        row['MaterialSampleCuration.access_constraints'] = None
        row['MaterialSampleCuration.curation_location'] = None
        
        self.rows.append(row)
        return row_id
    
    def create_sample_relation(self, relation_id: int, relation_data: Dict) -> int:
        """Create SampleRelation and return its row_id."""
        key = f"relation:{relation_id}"
        
        # Check if already created
        existing_id = self.registry.get_id('SampleRelation', key)
        if existing_id:
            return existing_id
        
        # Register and create row
        row_id = self.registry.register('SampleRelation', key)
        
        row = self.get_blank_row()
        row['row_id'] = row_id
        row['otype'] = 'SampleRelation'
        row['SampleRelation.label'] = relation_data.get('label', '')
        row['SampleRelation.relationship'] = relation_data.get('relationship', '')
        row['SampleRelation.target'] = relation_data.get('target', '')
        row['SampleRelation.description'] = relation_data.get('description', '')
        
        self.rows.append(row)
        return row_id
    
    # ========================================================================
    # Main Processing
    # ========================================================================
    
    def process_sample(self, igsn: str):
        """Process a single sample and create all related objects."""
        # Get sample with all joins
        query = """
            SELECT s.*,
                   l.name as locality_name,
                   sft2.label as locality_feature_type,
                   sft.label as sampled_feature_label,
                   sft.feature_type_uri as sampled_feature_uri,
                   gmt.label as general_material_label,
                   gmt.material_type_uri as general_material_uri,
                   st.label as sample_type_label,
                   st.sample_type_uri as sample_type_uri_value,
                   cm.label as collection_method_label,
                   p.label as platform_label,
                   lp.label as launch_platform_label,
                   cfi.label as cruise_field_prgrm_label,
                   gay.label as geologic_age_younger_label,
                   gay.geologic_time_interval_uri as geologic_age_younger_uri,
                   gao.label as geologic_age_older_label,
                   gao.geologic_time_interval_uri as geologic_age_older_uri,
                   cr.individual_id as cur_registrant_individual_id,
                   cr.institution_id as cur_registrant_institution_id,
                   co.individual_id as cur_owner_individual_id,
                   co.institution_id as cur_owner_institution_id
            FROM sample s
            LEFT JOIN locality l ON s.locality_id = l.locality_id
            LEFT JOIN sampled_feature_type sft ON s.sampled_feature_type_id = sft.feature_type_id
            LEFT JOIN material_type gmt ON s.general_material_type_id = gmt.material_type_id
            LEFT JOIN sample_type st ON s.sample_type_id = st.sample_type_id
            LEFT JOIN sampling_method cm ON s.collection_method_id = cm.collection_method_id
            LEFT JOIN platform p ON s.platform_id = p.platform_id
            LEFT JOIN platform lp ON s.launch_platform_id = lp.platform_id
            LEFT JOIN initiative cfi ON s.cruise_field_prgrm_id = cfi.initiative_id
            LEFT JOIN geologic_time_scale gay ON s.geologic_age_younger_id = gay.geologic_time_id
            LEFT JOIN geologic_time_scale gao ON s.geologic_age_older_id = gao.geologic_time_id
            LEFT JOIN sesar_user cr ON s.cur_registrant_id = cr.sesar_user_id
            LEFT JOIN sesar_user co ON s.cur_owner_id = co.sesar_user_id
            LEFT JOIN sampled_feature_type sft2 ON L.feature_type_id = sft2.feature_type_id
           WHERE s.igsn = %s
        """
        
        sample = self.execute_pg_query_one(query, (igsn,))
        if not sample:
            logger.warning(f"Sample {igsn} not found")
            return
        
        sample_id = sample['sample_id']
        
        # Create MaterialSampleRecord
        sample_key = f"sample:{sample_id}"
        sample_row_id = self.registry.register('MaterialSampleRecord', sample_key)
        
        # Create related objects and collect their IDs
        
        # Context category
        context_category_ids = []
        if sample.get('sampled_feature_type_id'):
            concept_id = self.create_concept(
                'sampled_feature_type',
                sample['sampled_feature_type_id'],
                sample.get('sampled_feature_label', ''),
                'SESAR Sampled Feature Type',
                sample.get('sampled_feature_uri')
            )
            context_category_ids.append(concept_id)
        
        # Material categories
        material_category_ids = []
        if sample.get('general_material_type_id'):
            concept_id = self.create_concept(
                'material_type',
                sample['general_material_type_id'],
                sample.get('general_material_label', ''),
                'SESAR Material Type',
                sample.get('general_material_uri')
            )
            material_category_ids.append(concept_id)
        
        # Sample object type
        sample_obj_type_ids = []
        if sample.get('sample_type_id'):
            concept_id = self.create_concept(
                'sample_type',
                sample['sample_type_id'],
                sample.get('sample_type_label', ''),
                'SESAR Sample Type',
                sample.get('sample_type_uri_value')
            )
            sample_obj_type_ids.append(concept_id)
        
        # Keywords (geologic ages and unit)
        keyword_ids = []
        if sample.get('geologic_unit'):
            concept_id = self.create_concept(
                'geologic_unit',
                sample_id,
                sample['geologic_unit'],
                'Geologic Unit'
            )
            keyword_ids.append(concept_id)
        
        if sample.get('geologic_age_younger_id'):
            concept_id = self.create_concept(
                'geologic_time_younger',
                sample['geologic_age_younger_id'],
                sample.get('geologic_age_younger_label', ''),
                'Geologic Age Younger',
                identifier=sample.get('geologic_age_younger_uri')
            )
            keyword_ids.append(concept_id)
        
        if sample.get('geologic_age_older_id'):
            concept_id = self.create_concept(
                'geologic_time_older',
                sample['geologic_age_older_id'],
                sample.get('geologic_age_older_label', ''),
                'Geologic Age Older',
                identifier=sample.get('geologic_age_older_uri')
            )
            keyword_ids.append(concept_id)
        
        # Registrant
        registrant_ids = []
        if sample.get('cur_registrant_individual_id'):
            agent_id = self.create_agent('individual', sample['cur_registrant_individual_id'], 'registrant')
            if agent_id:
                registrant_ids.append(agent_id)
        elif sample.get('cur_registrant_institution_id'):
            agent_id = self.create_agent('institution', sample['cur_registrant_institution_id'], 'registrant')
            if agent_id:
                registrant_ids.append(agent_id)
        
        # Curation
        curation_ids = []
        curation_id = self.create_curation(sample_id, sample)
        if curation_id:
            curation_ids.append(curation_id)
        
        # Sampling event
        produced_by_ids = []
        event_id = self.create_sampling_event(sample_id, sample)
        if event_id:
            produced_by_ids.append(event_id)
        
        # Related resources (parent, children, siblings)
        related_resource_ids = []
        # This would require additional queries to get parent/child relationships
        
        # Build description
        desc_parts = []
        if sample.get('sample_description'):
            desc_parts.append(sample['sample_description'])
        if sample.get('size'):
            desc_parts.append(f"Sample size: {sample['size']}")
        
        description = '. '.join(desc_parts) if desc_parts else None
        
        # Create MaterialSampleRecord row
        row = self.get_blank_row()
        row['row_id'] = sample_row_id
        row['otype'] = 'MaterialSampleRecord'
        row['tcreated'] = time.time()
        row['MaterialSampleRecord.label'] = sample.get('name')
        row['MaterialSampleRecord.sample_identifier'] = sample.get('igsn')
        row['MaterialSampleRecord.description'] = description
        row['MaterialSampleRecord.last_modified_time'] = self.format_iso8601(sample.get('last_update_date'))
        row['MaterialSampleRecord.sampling_purpose'] = sample.get('purpose')
        row['MaterialSampleRecord.schema'] = 'iSamplesSchemaCore1.0.json'
        row['MaterialSampleRecord.has_context_category'] = context_category_ids if context_category_ids else None
        row['MaterialSampleRecord.has_material_category'] = material_category_ids if material_category_ids else None
        row['MaterialSampleRecord.has_sample_object_type'] = sample_obj_type_ids if sample_obj_type_ids else None
        row['MaterialSampleRecord.keywords'] = keyword_ids if keyword_ids else None
        row['MaterialSampleRecord.registrant'] = registrant_ids if registrant_ids else None
        row['MaterialSampleRecord.curation'] = curation_ids if curation_ids else None
        row['MaterialSampleRecord.produced_by'] = produced_by_ids if produced_by_ids else None
        row['MaterialSampleRecord.related_resource'] = related_resource_ids if related_resource_ids else None
        
        self.rows.append(row)
        logger.info(f"Processed sample {igsn} (row_id: {sample_row_id})")
    
    def process_all_samples(self, limit: Optional[int] = None):
        """Process all samples in the database."""
        query = "SELECT igsn FROM sample"
        if limit:
            query += f" LIMIT {limit}"
        
        samples = self.execute_pg_query(query)
        logger.info(f"Processing {len(samples)} samples")
        
        for i, sample in enumerate(samples, 1):
            self.process_sample(sample['igsn'])
            if i % 100 == 0:
                logger.info(f"Processed {i}/{len(samples)} samples")
    
    def write_to_duckdb(self):
        """Write all rows to DuckDB."""
        if not self.rows:
            logger.warning("No rows to write")
            return
        
        logger.info(f"Writing {len(self.rows)} rows to DuckDB")
        
        # Insert rows in batches
        batch_size = 1000
        for i in range(0, len(self.rows), batch_size):
            batch = self.rows[i:i+batch_size]
            self.duck_conn.executemany(
                "INSERT INTO samples VALUES (" + ",".join(["?"] * len(self.get_blank_row())) + ")",
                [tuple(row.values()) for row in batch]
            )
            self.duck_conn.commit()
        
        logger.info("Data written to DuckDB")
    
    def export_to_parquet(self):
        """Export DuckDB table to Parquet file."""
        output_path = pathlib.Path(self.config.output_parquet)
        
        query = f"""
            COPY samples TO '{output_path}' (FORMAT PARQUET)
        """
        
        self.duck_conn.execute(query)
        logger.info(f"Exported to {output_path}")
    
    def run(self, limit: Optional[int] = None):
        """Main execution method."""
        try:
            self.connect_postgres()
            self.connect_duckdb()
            
            self.process_all_samples(limit=limit)
            self.write_to_duckdb()
            self.export_to_parquet()
            
            logger.info("Conversion complete!")
            
        finally:
            if self.pg_conn:
                self.pg_conn.close()
            if self.duck_conn:
                self.duck_conn.close()


# ============================================================================
# Main
# ============================================================================

def main():
    # config = DatabaseConfig(
    #     pg_database="SESAR202504",
    #     pg_user="postgres",
    #     pg_password="smrpostgis",
    #     duck_database="sesar_samples.ddb",
    #     output_parquet="sesar_samples.parquet"
    # )
    
    converter = SESARToParquetConverter()
    
    # Process just a few samples for testing
    converter.run(limit=10)
    
    # Or process all samples:
    # converter.run()


if __name__ == "__main__":
    main()
