-- Helper function to remove null values from JSON objects
CREATE OR REPLACE FUNCTION remove_nulls(input_json jsonb)
RETURNS jsonb AS $$
    SELECT jsonb_object_agg(key, value)
    FROM jsonb_each(input_json)
    WHERE value IS NOT NULL
      AND value != 'null'::jsonb
      AND value != '[]'::jsonb
      AND (value::text != '{}' OR jsonb_typeof(value) != 'object')
$$ LANGUAGE SQL IMMUTABLE;

-- Main query with null filtering (using jsonb consistently)
-- generated by claude-code, based on starter SQL by SMR; my code
--  did not remove null values, claude added the remove nulls function and
--  restructured.
-- this version for testing, has limit 10, no WHERE clause
SELECT
    remove_nulls(jsonb_build_object(
        '$schema', '../src/schemas/iSamplesSchemaCore2.0.json',
        'pid', CONCAT('sesar.', s.sample_id::text),
        'sample_identifier', s.igsn,
        'label', s.name,
        'description', NULLIF(CONCAT_WS('; ',
                    CASE WHEN s.sample_description IS NOT NULL THEN 'Sample description: ' || s.sample_description END,
                    CASE WHEN s.material_name_verbatim IS NOT NULL THEN 'Material verbatim: ' || s.material_name_verbatim END,
                    CASE WHEN s.geologic_age_verbatim IS NOT NULL THEN 'Age verbatim: ' || s.geologic_age_verbatim END,
                    CASE WHEN s.numeric_age_min IS NOT NULL THEN 'Age min: ' || s.numeric_age_min::TEXT END,
                    CASE WHEN s.numeric_age_max IS NOT NULL THEN 'Age max: ' || s.numeric_age_max::TEXT END,
                    CASE WHEN s.numeric_age_unit IS NOT NULL THEN 'Age units: ' || s.numeric_age_unit END
                ), ''),
        'alternate_identifiers', CASE
            WHEN EXISTS (SELECT 1 FROM sample_additional_name san WHERE san.sample_id = s.sample_id) THEN
                (SELECT jsonb_agg(CONCAT(san.name_authority,'.',san.name))
                 FROM sample_additional_name san
                 WHERE san.sample_id = s.sample_id)
            ELSE NULL
        END,
        'produced_by', CASE
            WHEN s.collection_end_date IS NOT NULL
              OR s.primary_location_type IS NOT NULL
              OR s.latitude IS NOT NULL
              OR s.longitude IS NOT NULL
              OR s.elevation IS NOT NULL
              OR cfi.label IS NOT NULL
              OR cm.label IS NOT NULL
              OR p.label IS NOT NULL
              OR lp.label IS NOT NULL
              OR s.launch_label IS NOT NULL
              OR s.locality_description IS NOT NULL
              OR s.location_description IS NOT NULL
              OR s.primary_location_name IS NOT NULL
              OR POSITION('Legacy collector' IN COALESCE(s.collection_method_detail, '')) > 0
            THEN remove_nulls(jsonb_build_object(
                'pid', CONCAT('event.', s.sample_id::text),
                'label', 'sampling event',
                'description', NULLIF(CONCAT_WS('; ',
                      CASE WHEN cm.label IS NOT NULL THEN 'Collection method: ' || cm.label END,
                      CASE WHEN length(s.collection_method_detail) > 1  THEN 'Method detail: '
                            || trim(both ' .' FROM split_part(s.collection_method_detail, 'Legacy collector:', 1)) END,
                      CASE WHEN p.label IS NOT NULL THEN 'Platform: ' || p.label END,
                      CASE WHEN lp.label IS NOT NULL THEN 'Launch platform: ' || lp.label END,
                      CASE WHEN s.launch_label IS NOT NULL THEN 'Launch: ' || s.launch_label END), ''),
                'has_feature_of_interest', s.primary_location_type,
                'project', cfi.label,
                'responsibility', CASE
                    WHEN POSITION('Legacy collector' IN COALESCE(s.collection_method_detail, '')) > 0 THEN
                        jsonb_build_array(
                            remove_nulls(
                                jsonb_build_object(
                                    'name', trim(both ' .' FROM split_part(s.collection_method_detail, 'Legacy collector:', 2)),
                                    'role', 'collector'
                                )
                            )
                        )

                    ELSE '[]'::jsonb   -- return empty array instead of NULL
                END,
                'result_time', s.collection_end_date,
                'sample_location', CASE
                    WHEN s.latitude IS NOT NULL OR s.longitude IS NOT NULL OR s.elevation IS NOT NULL THEN
                        remove_nulls(jsonb_build_object(
                            'elevation', CASE WHEN s.elevation IS NOT NULL
                                THEN concat(s.elevation, ' ', s.elevation_unit) END,
                            'latitude', s.latitude,
                            'longitude', s.longitude,
                            'obfuscated', CASE WHEN s.latitude IS NOT NULL OR s.longitude IS NOT NULL
                                THEN FALSE ELSE NULL END
                        ))
                    ELSE NULL
                END,
                'sampling_site', CASE
                    WHEN s.locality_description IS NOT NULL
                      OR s.location_description IS NOT NULL
                      OR s.depth_min IS NOT NULL
                      OR s.depth_max IS NOT NULL
                      OR s.depth_scale IS NOT NULL
                      OR s.vertical_datum IS NOT NULL
                      OR s.primary_location_name IS NOT NULL
                      OR s.city IS NOT NULL
                      OR s.county IS NOT NULL
                      OR s.province IS NOT NULL
                      OR cty.label IS NOT NULL
                      OR cnt.label IS NOT NULL
                    THEN remove_nulls(jsonb_build_object(
                        'description', NULLIF(CONCAT_WS('; ',
                            CASE WHEN s.locality_description IS NOT NULL THEN 'Locality: ' || s.locality_description END,
                            CASE WHEN s.location_description IS NOT NULL THEN 'Location: ' || s.location_description END,
                            CASE WHEN s.depth_min IS NOT NULL THEN 'Depth_min: ' || s.depth_min END,
                            CASE WHEN s.depth_max IS NOT NULL THEN 'Depth_max: ' || s.depth_max END,
                            CASE WHEN s.depth_scale IS NOT NULL THEN 'Depth_scale: ' || s.depth_scale END,
                            CASE WHEN s.vertical_datum IS NOT NULL THEN 'Vertical_datum: ' || s.vertical_datum END
                        ), ''),
                        'place_name', CASE
                            WHEN s.primary_location_name IS NOT NULL
                              OR s.city IS NOT NULL
                              OR s.county IS NOT NULL
                              OR s.province IS NOT NULL
                              OR cty.label IS NOT NULL
                              OR cnt.label IS NOT NULL
                            THEN (
                                SELECT jsonb_agg(place)
                                FROM (
                                    SELECT unnest(ARRAY[
                                        s.primary_location_name,
                                        s.city,
                                        s.county,
                                        s.province,
                                        cty.label,
                                        cnt.label
                                    ]) AS place
                                ) sub
                                WHERE place IS NOT NULL
                            )
                            ELSE NULL
                        END
                    ))
                    ELSE NULL
                END
            ))
            ELSE NULL
        END,
        'sampling_purpose', s.purpose,
        'has_context_category', CASE
            WHEN COUNT(*) FILTER (WHERE s.sample_id IS NOT NULL) > 0 THEN
                jsonb_agg(
                    jsonb_build_object(
                        'label', 'missing',
                        'pid', 'http://www.opengis.net/def/nil/OGC/0/missing',
                        'scheme_name', 'OGC nil values'
                    )
                )
            ELSE NULL
        END,
        'has_material_category', CASE
            WHEN gmt.label IS NOT NULL OR lc.label IS NOT NULL THEN
                (SELECT jsonb_agg(mat)
                 FROM (
                     SELECT remove_nulls(jsonb_build_object(
                         'label', gmt.label,
                         'pid', gmt.material_type_uri,
                         'scheme_name', gmt.scheme_uri
                     )) AS mat
                     WHERE gmt.label IS NOT NULL
                     UNION ALL
                     SELECT remove_nulls(jsonb_build_object(
                         'label', lc.label,
                         'pid', lc.material_type_uri,
                         'scheme_name', lc.scheme_uri
                     )) AS mat
                     WHERE lc.label IS NOT NULL
                 ) materials
                 WHERE mat IS NOT NULL AND mat != '{}'::jsonb
                )
            ELSE NULL
        END,
        'has_sample_object_type', CASE
            WHEN st.label IS NOT NULL THEN
                jsonb_agg(
                    remove_nulls(jsonb_build_object(
                        'label', st.label,
                        'pid', st.uri,
                        'scheme_name', st.scheme_name
                    ))
                ) FILTER (WHERE st.label IS NOT NULL)
            ELSE NULL
        END,
        'keywords', CASE
            WHEN gay.label IS NOT NULL OR gao.label IS NOT NULL THEN
                (SELECT jsonb_agg(kw)
                 FROM (
                     SELECT remove_nulls(jsonb_build_object(
                         'label', gay.label,
                         'pid', gay.geologic_time_interval_uri,
                         'scheme_uri', gay.scheme_uri
                     )) AS kw
                     WHERE gay.label IS NOT NULL
                     UNION ALL
                     SELECT remove_nulls(jsonb_build_object(
                         'label', gao.label,
                         'pid', gao.geologic_time_interval_uri,
                         'scheme_uri', gao.scheme_uri
                     )) AS kw
                     WHERE gao.label IS NOT NULL
                 ) keywords_sub
                 WHERE kw IS NOT NULL AND kw != '{}'::jsonb
                )
            ELSE NULL
        END,
        'related_resource', CASE
            WHEN EXISTS (
                SELECT 1
                FROM related_resource_connection rc
                LEFT JOIN related_resource rres ON rc.related_resource_id = rres.id
                WHERE s.sample_id = rc.sample_id AND rres.label IS NOT NULL
            ) THEN
                (SELECT jsonb_agg(
                    remove_nulls(jsonb_build_object(
                        'label', rres.label,
                        'relationship', 'repository file',
                        'target', rres.uri
                    ))
                 )
                 FROM related_resource_connection rc
                 LEFT JOIN related_resource rres ON rc.related_resource_id = rres.id
                 WHERE s.sample_id = rc.sample_id AND rres.label IS NOT NULL
                )
            ELSE NULL
        END,
        'curation', CASE
            WHEN EXISTS (SELECT 1 FROM sample_source_record ssr WHERE ssr.sample_id = s.sample_id)
              OR EXISTS (SELECT 1 FROM individual ind WHERE co.individual_id = ind.individual_id)
            THEN remove_nulls(jsonb_build_object(
                'access_constraints', jsonb_agg('not specified'::TEXT),
                'curation_location', (
                    SELECT data -> 'archival_information' ->> 'current_archive' AS current_archive
                    FROM sample_source_record ssr
                    WHERE ssr.sample_id = s.sample_id
                ),
                'responsibility', CASE
                    WHEN EXISTS (SELECT 1 FROM individual ind WHERE co.individual_id = ind.individual_id AND ind.label IS NOT NULL)
                    THEN (SELECT jsonb_agg(
                        remove_nulls(jsonb_build_object(
                            'name', ind.label,
                            'contact_information', ind.email,
                            'pid', CASE WHEN ind.individual_uri IS NOT NULL
                                THEN 'orcid: ' || ind.individual_uri END,
                            'role', 'owner'
                        ))
                    )
                    FROM individual ind
                    WHERE co.individual_id = ind.individual_id AND ind.label IS NOT NULL
                    )
                    ELSE NULL
                END
            ))
            ELSE NULL
        END,
        'last_modified_time',  s.last_update_date,
,
        'registrant', CASE
            WHEN cr.individual_id IS NOT NULL AND EXISTS (
                SELECT 1 FROM individual ind
                WHERE cr.individual_id = ind.individual_id AND ind.label IS NOT NULL
            ) THEN
                (SELECT remove_nulls(jsonb_build_object(
                    'name', ind.label,
                    'contact_information', ind.email,
                    'pid', CASE WHEN ind.individual_uri IS NOT NULL
                        THEN 'orcid: ' || ind.individual_uri END
                ))
                FROM individual ind
                WHERE cr.individual_id = ind.individual_id
                )
            ELSE NULL
        END
    ))::json as isample_json
FROM
     sample s
    LEFT JOIN material_type gmt ON s.general_material_type_id = gmt.material_type_id
    LEFT JOIN material_type lc ON s.legacy_classification_id = lc.material_type_id
    LEFT JOIN object_type st ON s.object_type_id = st.id
    LEFT JOIN sampling_method cm ON s.collection_method_id = cm.collection_method_id
    LEFT JOIN platform p ON s.platform_id = p.id
    LEFT JOIN launch_platform lp ON s.launch_platform_id = lp.id
    LEFT JOIN initiative cfi ON s.cruise_field_prgrm_id = cfi.id
    LEFT JOIN geologic_time_scale gay ON s.geologic_age_younger_id = gay.geologic_time_id
    LEFT JOIN geologic_time_scale gao ON s.geologic_age_older_id = gao.geologic_time_id
    LEFT JOIN sesar_user cr ON s.cur_registrant_id = cr.sesar_user_id
    LEFT JOIN sesar_user co ON s.cur_owner_id = co.sesar_user_id
    LEFT JOIN country cty ON s.country_id = cty.id
    LEFT JOIN continent cnt ON cty.continent_id = cnt.id
GROUP BY s.sample_id, s.igsn, s.name, s.sample_description, s.material_name_verbatim,
    s.geologic_age_verbatim, s.numeric_age_min, s.numeric_age_max, s.numeric_age_unit,
    s.collection_method_detail, s.primary_location_type, s.collection_end_date,
    s.latitude, s.longitude, s.elevation, s.elevation_unit,
    s.locality_description, s.location_description, s.depth_min, s.depth_max,
    s.depth_scale, s.vertical_datum, s.primary_location_name, s.city, s.county,
    s.province, s.purpose, s.launch_label,
    cm.label, p.label, lp.label, cfi.label, cty.label, cnt.label,
    gmt.label, gmt.material_type_uri, gmt.scheme_uri,
    lc.label, lc.material_type_uri, lc.scheme_uri,
    st.label, st.uri, st.scheme_name,
    gay.label, gay.geologic_time_interval_uri, gay.scheme_uri,
    gao.label, gao.geologic_time_interval_uri, gao.scheme_uri,
    co.individual_id, cr.individual_id
LIMIT 10;