"""
Standalone function to extract SESAR sample data and format as iSamples JSON.
No Django dependencies - uses direct PostgreSQL queries.
Generated by Claude-code based on sesar2025migrate/newdb/models.py, views.py,
and sesar2025migrate/templates/newdbtemplate/sample.json
SMR 2025-12-10
set up to work with 202504 version of SESAR database, before dumbing down.
"""
import psycopg2
from psycopg2.extras import RealDictCursor
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
import json
import datetime


@dataclass
class DatabaseConfig:
    """Database connection configuration."""
    database: str = "SESAR202504"
    user: str = "postgres"
    password: str = "your_password"
    host: str = "127.0.0.1"
    port: int = 5432


class SESARJSONExtractor:
    """Extracts SESAR sample data and formats as iSamples JSON."""
    
    def __init__(self, db_config: DatabaseConfig):
        self.db_config = db_config
        self.conn = None
    
    def connect(self):
        """Establish database connection."""
        self.conn = psycopg2.connect(
            database=self.db_config.database,
            user=self.db_config.user,
            password=self.db_config.password,
            host=self.db_config.host,
            port=self.db_config.port,
        )
    
    def close(self):
        """Close database connection."""
        if self.conn:
            self.conn.close()
    
    def execute_query(self, query: str, params: tuple = None) -> List[Dict]:
        """Execute query and return results as list of dictionaries."""
        with self.conn.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, params)
            return cursor.fetchall()
    
    def execute_query_one(self, query: str, params: tuple = None) -> Optional[Dict]:
        """Execute query and return single result as dictionary."""
        with self.conn.cursor(cursor_factory=RealDictCursor) as cursor:
            cursor.execute(query, params)
            result = cursor.fetchone()
            return dict(result) if result else None

    def format_iso8601(self, date_value) -> Optional[str]:
        """Convert date to ISO8601 format with 'T' separator."""
        if not date_value:
            return None

        try:
            # If it's already a datetime object
            if isinstance(date_value, datetime):
                return date_value.isoformat()

            # If it's a string, parse and convert
            if isinstance(date_value, str):
                dt = datetime.fromisoformat(date_value)
                return dt.isoformat()

            return str(date_value)
        except Exception as e:
            # Fallback: simple string replace
            return str(date_value).replace(' ', 'T', 1)
    # ========================================================================
    # Query Methods for Related Data
    # ========================================================================
    
    def get_sample_by_igsn(self, igsn: str) -> Optional[Dict]:
        """Get main sample record by IGSN."""
        query = """
            SELECT s.*,
                   s.primary_location_name name as locality_name,
                   s.locality_detail as locality_detail_full,
                   sft.label as sampled_feature_label,
                   gmt.label as general_material_label,
                   gmt.material_type_uri as general_material_uri,
                   st.label as sample_type_label,
                   st.sample_type_uri as sample_type_uri_value,
                   cm.label as collection_method_label,
                   p.label as platform_label,
                   lp.label as launch_platform_label,
                   cfi.label as cruise_field_prgrm_label,
                   gay.label as geologic_age_younger_label,
                   gay.geologic_time_interval_uri as geologic_age_younger_uri,
                   gao.label as geologic_age_older_label,
                   gao.geologic_time_interval_uri as geologic_age_older_uri,
                   cr.individual_id as cur_registrant_individual_id,
                   cr.institution_id as cur_registrant_institution_id,
                   co.individual_id as cur_owner_individual_id,
                   co.institution_id as cur_owner_institution_id
            FROM sample s
            LEFT JOIN material_type gmt ON s.general_material_type_id = gmt.material_type_id
            LEFT JOIN sample_type st ON s.sample_type_id = st.sample_type_id
            LEFT JOIN sampling_method cm ON s.collection_method_id = cm.collection_method_id
            LEFT JOIN platform p ON s.platform_id = p.platform_id
            LEFT JOIN platform lp ON s.launch_platform_id = lp.platform_id
            LEFT JOIN initiative cfi ON s.cruise_field_prgrm_id = cfi.initiative_id
            LEFT JOIN geologic_time_scale gay ON s.geologic_age_younger_id = gay.geologic_time_id
            LEFT JOIN geologic_time_scale gao ON s.geologic_age_older_id = gao.geologic_time_id
            LEFT JOIN sesar_user cr ON s.cur_registrant_id = cr.sesar_user_id
            LEFT JOIN sesar_user co ON s.cur_owner_id = co.sesar_user_id
            LEFT JOIN sampled_feature_type sft2 ON L.feature_type_id = sft2.feature_type_id
            WHERE s.igsn = %s
        """
        return self.execute_query_one(query, (igsn,))

    def get_additional_names(self, sample_id: int) -> List[str]:
        """Get additional names for sample."""
        query = """
            SELECT name FROM sample_additional_name 
            WHERE sample_id = %s
        """
        results = self.execute_query(query, (sample_id,))
        return [r['name'] for r in results] if results else []
    
    def get_parent_sample(self, sample_id: int) -> Optional[Dict]:
        """Get parent sample relationship."""
        query = """
            SELECT rr.*, s.igsn as parent_igsn, s.name as parent_name
            FROM related_resource rr
            LEFT JOIN sample s ON rr.related_sesar_sample_id = s.sample_id
            WHERE rr.sample_id = %s AND rr.relation_type_id = 1
        """
        return self.execute_query_one(query, (sample_id,))
    
    def get_sibling_samples(self, sample_id: int, parent_id: int) -> List[Dict]:
        """Get sibling samples (same parent)."""
        query = """
            SELECT rr.*, s.igsn as sibling_igsn, s.name as sibling_name
            FROM related_resource rr
            JOIN sample s ON rr.sample_id = s.sample_id
            WHERE rr.related_sesar_sample_id = %s 
            AND rr.relation_type_id = 1
            AND rr.sample_id != %s
        """
        return self.execute_query(query, (parent_id, sample_id))
    
    def get_child_samples(self, sample_id: int) -> List[Dict]:
        """Get child samples."""
        query = """
            SELECT rr.*, s.igsn as child_igsn, s.name as child_name
            FROM related_resource rr
            JOIN sample s ON rr.sample_id = s.sample_id
            WHERE rr.related_sesar_sample_id = %s 
            AND rr.relation_type_id = 1
        """
        return self.execute_query(query, (sample_id,))
    
    def get_geospatial_location(self, sample_id: int) -> Optional[Dict]:
        """Get geospatial location (UTM coordinates)."""
        query = """
            SELECT * FROM geospatial_location 
            WHERE sample_id = %s
        """
        return self.execute_query_one(query, (sample_id,))
    
    def get_sample_materials(self, sample_id: int) -> List[Dict]:
        """Get additional material types for sample."""
        query = """
            SELECT sm.*, mt.label, mt.material_type_uri
            FROM sample_material sm
            JOIN material_type mt ON sm.material_type_id = mt.material_type_id
            WHERE sm.sample_id = %s
        """
        return self.execute_query(query, (sample_id,))
    
    def get_responsible_parties(self, sample_id: int) -> List[Dict]:
        """Get responsible parties (agents) for sample."""
        query = """
            SELECT rsa.*,
                   rt.label as relation_type_label,
                   i.label as individual_label,
                   i.individual_uri,
                   inst.label as institution_label
            FROM related_sample_agent rsa
            LEFT JOIN relation_type rt ON rsa.relation_type_id = rt.relation_type_id
            LEFT JOIN individual i ON rsa.individual_id = i.individual_id
            LEFT JOIN institution inst ON rsa.institution_id = inst.institution_id
            WHERE rsa.sample_id = %s
        """
        return self.execute_query(query, (sample_id,))
    
    def get_current_archive(self, sample_id: int) -> Optional[Dict]:
        """Get current archive (relation_type_id = 3)."""
        query = """
            SELECT rsa.*,
                   i.label as individual_label,
                   i.individual_uri,
                   inst.label as institution_label
            FROM related_sample_agent rsa
            LEFT JOIN individual i ON rsa.individual_id = i.individual_id
            LEFT JOIN institution inst ON rsa.institution_id = inst.institution_id
            WHERE rsa.sample_id = %s AND rsa.relation_type_id = 3
        """
        return self.execute_query_one(query, (sample_id,))
    
    def get_registrant(self, sesar_user_id: int) -> Optional[Dict]:
        """Get registrant from sesar_user."""
        query = """
            SELECT su.*,
                   i.label as individual_label,
                   inst.label as institution_label
            FROM sesar_user su
            LEFT JOIN individual i ON su.individual_id = i.individual_id
            LEFT JOIN institution inst ON su.institution_id = inst.institution_id
            WHERE su.sesar_user_id = %s
        """
        return self.execute_query_one(query, (sesar_user_id,))
    
    def get_publication_urls(self, sample_id: int) -> List[Dict]:
        """Get publication URLs for sample."""
        query = """
            SELECT * FROM sample_publication_url 
            WHERE sample_id = %s
        """
        return self.execute_query(query, (sample_id,))
    
    def get_sample_docs(self, sample_id: int) -> List[Dict]:
        """Get sample documents."""
        query = """
            SELECT * FROM sample_doc 
            WHERE sample_id = %s
        """
        return self.execute_query(query, (sample_id,))
    
    # ========================================================================
    # Helper Methods for Building JSON Structure
    # ========================================================================
    
    def build_collection_description(self, sample: Dict) -> str:
        """Build collection description string."""
        parts = []
        
        if sample.get('collection_method_label'):
            parts.append(f"method:{sample['collection_method_label']}")
        
        if sample.get('collection_method_detail'):
            parts.append(sample['collection_method_detail'])
        
        if sample.get('platform_label'):
            parts.append(f"Platform: {sample['platform_label']}")
        
        if sample.get('launch_platform_label'):
            parts.append(f"Launch Platform: {sample['launch_platform_label']}")
        
        if sample.get('launch_label'):
            parts.append(f"Launch: {sample['launch_label']}")
        
        return '. '.join(parts) if parts else ''
    
    def build_vertical_position(self, sample: Dict) -> str:
        """Build vertical position string."""
        parts = []
        
        if sample.get('elevation'):
            parts.append(str(sample['elevation']))
            if sample.get('elevation_uom'):
                parts.append(f"UOM: {sample['elevation_uom']}")
        
        depth_min = sample.get('depth_min')
        depth_max = sample.get('depth_max')
        
        if depth_min or depth_max:
            if depth_min == depth_max:
                parts.append(f"Depth: {depth_min}")
            elif depth_min and depth_max:
                parts.append(f"Depth range: {depth_min} to {depth_max}")
            elif depth_min:
                parts.append(f"Depth minimum: {depth_min}")
            elif depth_max:
                parts.append(f"Depth maximum: {depth_max}")
            
            if sample.get('depth_uom'):
                parts.append(f"UOM: {sample['depth_uom']}")
        
        if sample.get('depth_spatial_ref'):
            parts.append(f"Datum: {sample['depth_spatial_ref']}")
        
        return ' '.join(parts) if parts else ''
    
    def build_sample_description(self, sample: Dict, coordinates: Optional[Dict]) -> str:
        """Build sample description string."""
        parts = []
        
        if sample.get('sample_description'):
            parts.append(sample['sample_description'])
        
        if sample.get('size'):
            parts.append(f"Sample size: {sample['size']}")
        
        # Lat/long ranges
        if sample.get('latitude') and sample.get('latitude_end'):
            parts.append(f"Latitude from {sample['latitude']} to {sample['latitude_end']}")
        
        if sample.get('longitude') and sample.get('longitude_end'):
            parts.append(f"Longitude from {sample['longitude']} to {sample['longitude_end']}")
        
        # UTM coordinates
        if coordinates:
            utm_parts = []
            if coordinates.get('coordinate_1'):
                utm_parts.append(f"Easting {coordinates['coordinate_1']}")
            if coordinates.get('coordinate_2'):
                utm_parts.append(f"Northing {coordinates['coordinate_2']}")
            if coordinates.get('spatial_reference_system'):
                utm_parts.append(f"Spatial reference: {coordinates['spatial_reference_system']}")
            
            if utm_parts:
                parts.append(f"UTM coordinates: {' '.join(utm_parts)}")
        
        # Numeric ages
        age_min = sample.get('numeric_age_min')
        age_max = sample.get('numeric_age_max')
        
        if age_min and age_max:
            parts.append(f"Age between {age_min} and {age_max}")
        elif age_min:
            parts.append(f"Minimum age {age_min}")
        elif age_max:
            parts.append(f"Maximum age {age_max}")
        
        if (age_min or age_max) and sample.get('numeric_age_unit'):
            parts.append(f"Age units {sample['numeric_age_unit']}")
        
        if sample.get('age_qualifier'):
            parts.append(f"Age qualifier: {sample['age_qualifier']}")
        
        return '. '.join(parts) if parts else ''
    
    # ========================================================================
    # Main JSON Building Method
    # ========================================================================
    
    def build_isamples_json(self, igsn: str) -> Optional[Dict]:
        """
        Build iSamples JSON structure for a sample.
        Args:
            igsn: Sample IGSN identifier
        Returns:
            Dictionary representing iSamples JSON structure
        """
        # Get main sample record
        sample = self.get_sample_by_igsn(igsn)
        if not sample:
            return None
        
        sample_id = sample['sample_id']
        
        # Get all related data
        alt_names = self.get_additional_names(sample_id)
        parent = self.get_parent_sample(sample_id)
        children = self.get_child_samples(sample_id)
        
        # Get siblings if there's a parent
        siblings = []
        if parent and parent.get('related_sesar_sample_id'):
            siblings = self.get_sibling_samples(sample_id, parent['related_sesar_sample_id'])
        
        coordinates = self.get_geospatial_location(sample_id)
        materials = self.get_sample_materials(sample_id)
        resp_parties = self.get_responsible_parties(sample_id)
        current_archive = self.get_current_archive(sample_id)
        
        # Filter out current archive from responsible parties
        if resp_parties and current_archive:
            resp_parties = [rp for rp in resp_parties if rp['relation_type_id'] != 3]
        
        registrant = None
        if sample.get('cur_registrant_individual_id'):
            registrant = self.get_registrant(sample['cur_registrant_id'])
        
        owner = None
        if sample.get('cur_owner_individual_id') or sample.get('cur_owner_institution_id'):
            owner = self.get_registrant(sample['cur_owner_id'])
        
        links = self.get_publication_urls(sample_id)
        docs = self.get_sample_docs(sample_id)
        
        # Build description components
        collection_desc = self.build_collection_description(sample)
        vertical_pos = self.build_vertical_position(sample)
        sam_desc = self.build_sample_description(sample, coordinates)
        
        # Build JSON structure
        json_output = {
            "@schema": "iSamplesSchemaCore1.0.json",
            "@id": sample.get('igsn', ''),
            "label": sample.get('name', 'sample name missing'),
            "sample_identifier": sample.get('igsn', ''),
            "description": sam_desc
        }
        
        # Add context category
        if sample.get('sampled_feature_label'):
            json_output["has_context_category"] = [{
                "label": sample['sampled_feature_label'],
                "identifier": sample.get('sampled_feature_uri', 'http://www.opengis.net/def/nil/OGC/0/missing')
            }]
        
        # Add material categories
        material_categories = []
        
        # Verbatim material name
        if sample.get('material_name_verbatim'):
            material_categories.append({
                "label": sample['material_name_verbatim'],
                "scheme_name": "verbatim"
            })
        else:
            material_categories.append({"label": "missing"})
        
        # General material type
        if sample.get('general_material_label'):
            material_categories.append({
                "label": sample['general_material_label'],
                "identifier": sample.get('general_material_uri', 'http://www.opengis.net/def/nil/OGC/0/missing')
            })
        
        # Additional materials
        for mat in materials:
            # Don't duplicate general material type
            if mat.get('material_type_id') != sample.get('general_material_type_id'):
                material_categories.append({
                    "label": mat.get('label', 'material name missing'),
                    "identifier": mat.get('material_type_uri', 'http://www.opengis.net/def/nil/OGC/0/missing')
                })
        
        json_output["has_material_category"] = material_categories
        
        # Add sample object type
        if sample.get('sample_type_label'):
            json_output["has_sample_object_type"] = [{
                "label": sample['sample_type_label'],
                "identifier": sample.get('sample_type_uri_value', 'http://www.opengis.net/def/nil/OGC/0/missing')
            }]
        
        # Build produced_by (sampling event)
        produced_by = {"label": "sampling event"}
        
        if collection_desc:
            produced_by["description"] = collection_desc
        
        if sample.get('locality_feature_type'):
            produced_by["has_feature_of_interest"] = sample['locality_feature_type']
        
        if sample.get('cruise_field_prgrm_label'):
            produced_by["project"] = sample['cruise_field_prgrm_label']
        
        # Add responsible parties
        if resp_parties:
            responsibility = []
            for agent in resp_parties:
                agent_name = agent.get('individual_label') or agent.get('institution_label', 'agentName missing')
                responsibility.append({
                    "role": agent.get('relation_type_label', 'related agent'),
                    "name": agent_name
                })
            produced_by["responsibility"] = responsibility
        
        # Add result time
        if sample.get('collection_start_date') or sample.get('collection_end_date'):
            result_time = sample.get('collection_start_date') or sample.get('collection_end_date')
            produced_by["result_time"] = self.format_iso8601(result_time)
        
        # Build sampling site
        sampling_site = {
            "label": sample.get('locality_name', 'site label missing'),
            "place_name": [sample.get('locality_name', 'place name missing')]
        }
        
        # Add site description
        desc_parts = []
        if sample.get('locality_detail'):
            desc_parts.append(sample['locality_detail'])
        if sample.get('location_qualifier'):
            desc_parts.append(sample['location_qualifier'])
        
        if desc_parts:
            sampling_site["description"] = '; '.join(desc_parts)
        
        # Add sample location
        if vertical_pos or sample.get('latitude') or sample.get('longitude'):
            sample_location = {}
            
            if vertical_pos:
                sample_location["elevation"] = vertical_pos
            
            if sample.get('latitude'):
                sample_location["latitude"] = float(sample['latitude'])
            
            if sample.get('longitude'):
                sample_location["longitude"] = float(sample['longitude'])
            
            sampling_site["sample_location"] = sample_location
        
        produced_by["sampling_site"] = sampling_site
        json_output["produced_by"] = produced_by
        
        # Add registrant
        if registrant:
            registrant_name = registrant.get('individual_label') or registrant.get('institution_label', 'agent name missing')
            json_output["registrant"] = {"name": registrant_name}
        
        # Add timestamps
        if sample.get('last_update_date'):
            json_output["last_modified_time"] = self.format_iso8601(sample['last_update_date'])
        
        # Add sampling purpose
        if sample.get('purpose'):
            json_output["sampling_purpose"] = sample['purpose']
        
        # Build related resources
        related_resources = []
        
        # Add parent
        if parent:
            related_resources.append({
                "label": parent.get('parent_name', 'parent'),
                "relationship": "Parent sample",
                "target": parent.get('related_resource_uri', 'http://www.opengis.net/def/nil/OGC/0/missing')
            })
        
        # Add children
        for child in children:
            related_resources.append({
                "label": child.get('child_name', 'child'),
                "relationship": "Child sample",
                "target": child.get('child_igsn', 'http://www.opengis.net/def/nil/OGC/0/missing')
            })
        
        # Add siblings
        for sib in siblings:
            related_resources.append({
                "label": sib.get('sibling_name', 'sibling'),
                "relationship": "Sample from the same parent",
                "target": sib.get('sibling_igsn', 'http://www.opengis.net/def/nil/OGC/0/missing')
            })
        
        # Add publication links
        for link in links:
            if link.get('description'):
                llabel = link.get('description')
            else:
                llabel = 'pub name missing'

            related_resources.append({
                "label": llabel,
                "relationship": "related resource",
                "target": link.get('url', 'http://www.opengis.net/def/nil/OGC/0/missing')
            })
        
        # Add documents
        for doc in docs:
            related_resources.append({
                "label": doc.get('file_name', 'file path missing'),
                "relationship": "local SESAR file",
                "description": "contact SESAR to access this file"
            })
        
        if related_resources:
            json_output["related_resource"] = related_resources
        
        # Add curation
        if current_archive:
            curation = {"role": "current archive"}
            
            if current_archive.get('institution_label'):
                curation["curation_location"] = current_archive['institution_label']
            
            if current_archive.get('individual_label'):
                responsibility = {"name": current_archive['individual_label']}
                if current_archive.get('individual_uri'):
                    responsibility["identifier"] = current_archive['individual_uri']
                curation["responsibility"] = responsibility
            
            json_output["curation"] = curation
        
        # Add keywords
        keywords = []
        
        if sample.get('geologic_unit'):
            keywords.append({
                "keyword": sample['geologic_unit'],
                "scheme_name": "Geologic unit"
            })
        
        if sample.get('geologic_age_younger_label'):
            keyword = {
                "keyword": sample['geologic_age_younger_label'],
                "scheme_name": "Geologic age, younger bound"
            }
            if sample.get('geologic_age_younger_uri'):
                keyword["keyword_uri"] = sample['geologic_age_younger_uri']
            keywords.append(keyword)
        
        if sample.get('geologic_age_older_label'):
            keyword = {
                "keyword": sample['geologic_age_older_label'],
                "scheme_name": "Geologic age, older bound"
            }
            if sample.get('geologic_age_older_uri'):
                keyword["keyword_uri"] = sample['geologic_age_older_uri']
            keywords.append(keyword)
        
        if keywords:
            json_output["keywords"] = keywords
        
        return json_output


# ============================================================================
# Standalone Function
# ============================================================================

def jsonFromSesar(
    igsn: str,
    database: str = "SESAR202504",
    user: str = "postgres",
    password: str = "smrpostgis",
    host: str = "127.0.0.1",
    port: int = 5432
) -> Optional[Dict]:
    """
    Extract sample data from SESAR database and format as iSamples JSON.
    
    This is a standalone function that queries PostgreSQL directly,
    without requiring Django or any ORM framework.
    
    Args:
        igsn: The sample IGSN identifier
        database: Database name
        user: Database user
        password: Database password
        host: Database host
        port: Database port
        
    Returns:
        Dictionary representing the iSamples JSON structure, or None if not found
        
    Example:
        >>> json_data = jsonFromSesar("IGSN12345", password="mypassword")
        >>> print(json.dumps(json_data, indent=2))
    """
    # Create database config
    db_config = DatabaseConfig(
        database=database,
        user=user,
        password=password,
        host=host,
        port=port
    )
    
    # Create extractor and get JSON
    extractor = SESARJSONExtractor(db_config)
    
    try:
        extractor.connect()
        json_output = extractor.build_isamples_json(igsn)
        return json_output
    except Exception as e:
        print(f"Error extracting sample data: {e}")
        raise
    finally:
        extractor.close()


# ============================================================================
# Usage Examples
# ============================================================================

if __name__ == "__main__":
    # Example 1: Simple usage
    json_data = jsonFromSesar(
        igsn="10.58052/RWM0001EF",
        password="smrpostgis"
    )
    
    if json_data:
        print(json.dumps(json_data, indent=2))
    else:
        print("Sample not found")
    
    
    # Example 2: Using the class directly for multiple queries
    db_config = DatabaseConfig(
        database="SESAR202504",
        user="postgres",
        password="smrpostgis"
    )
    
    extractor = SESARJSONExtractor(db_config)
    extractor.connect()
    
    try:
        # Process multiple samples
        igsns = ["IECDP5054EHY701", "ANOTHER_IGSN"]
        
        for igsn in igsns:
            json_data = extractor.build_isamples_json(igsn)
            if json_data:
                # Save to file
                with open(f"{igsn}.json", 'w') as f:
                    json.dump(json_data, f, indent=2)
                print(f"Saved {igsn}.json")
    finally:
        extractor.close()
