# Generated by Django 5.0.6 on 2025-03-18 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filters', models.JSONField()),
                ('search_time', models.DateTimeField()),
                ('search_by', models.ForeignKey(blank=True, db_column='search_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.sesaruser')),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
    ]
