# Generated by Django 5.0.6 on 2025-03-20 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0002_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesarspatialrefsys',
            name='proj4text',
        ),
        migrations.RemoveField(
            model_name='sesarspatialrefsys',
            name='srtext',
        ),
    ]
