# Generated by Django 5.0.6 on 2025-04-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0003_remove_sesarspatialrefsys_proj4text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='metadata_store_status',
            field=models.CharField(blank=True, db_comment='internal status flag used by SESAR to track metadata management', max_length=25, null=True),
        ),
    ]
