# Generated by Django 5.0.6 on 2025-04-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0004_alter_sample_metadata_store_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='locality_label',
            field=models.TextField(blank=True, db_comment='labels to identify a place, geographic, cultural, physiographic, geologic.include city, county, province, country if applicable and available. ', null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='locality',
            field=models.ForeignKey(blank=True, db_comment='link to place name description of sampling location, as opposed to a coordinate position. The locality table is incompeletly populated becauseof the challenges correlating the various place names and granularity of placenames. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.locality'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='locality_detail',
            field=models.TextField(blank=True, db_comment='linked locality entity has generalized information about the kind of locality; include details specific to this sampling location here. for legacy SESAR data this is concatenation of values from alllocation and locality fields.', null=True),
        ),
    ]
