# Generated by Django 5.0.6 on 2025-04-29 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0005_sample_locality_label_alter_sample_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='individual_collector',
            field=models.ManyToManyField(related_name='collected_samples', through='sesar_api.RelatedSampleAgent', to='sesar_api.individual'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='institution_collector',
            field=models.ManyToManyField(related_name='collected_samples', through='sesar_api.RelatedSampleAgent', to='sesar_api.institution'),
        ),
        migrations.AlterField(
            model_name='sampleadditionalname',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_names', to='sesar_api.sample'),
        ),
        migrations.AlterField(
            model_name='sampledoc',
            name='sample',
            field=models.ForeignKey(blank=True, db_comment='link to sample described by this URL content.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_docs', to='sesar_api.sample'),
        ),
        migrations.AlterField(
            model_name='samplepublicationurl',
            name='sample',
            field=models.ForeignKey(db_comment='link to sample described by this URL content.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='publication_urls', to='sesar_api.sample'),
        ),
    ]
