# Generated by Django 5.0.6 on 2025-05-05 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0006_alter_sample_individual_collector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedsampleagent',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_agents', to='sesar_api.sample'),
        ),
    ]
