# Generated by Django 5.0.6 on 2025-05-05 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0007_alter_relatedsampleagent_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='individual_collector',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='institution_collector',
        ),
    ]
