# Generated by Django 5.0.6 on 2025-05-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0009_add_sample_external_id_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedsampleagent',
            name='agent_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Team', 'Team'), ('Institution', 'Institution')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='igsn',
            field=models.CharField(db_comment='globally unique identifier string that identifies the material sample. In DataCite/DOI context, this includes the DOI prefix, and the identifier suffix (which in most cases begins with a SESAR code.', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='samplecollection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='relatedsampleagent',
            constraint=models.UniqueConstraint(condition=models.Q(('individual__isnull', False)), fields=('sample', 'relation_type', 'individual'), name='unique_individual_relation'),
        ),
        migrations.AddConstraint(
            model_name='relatedsampleagent',
            constraint=models.UniqueConstraint(condition=models.Q(('institution__isnull', False)), fields=('sample', 'relation_type', 'institution'), name='unique_institution_relation'),
        ),
        migrations.AddConstraint(
            model_name='relatedsampleagent',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('sample', 'relation_type', 'team'), name='unique_team_relation'),
        ),
        migrations.AddConstraint(
            model_name='sampleadditionalname',
            constraint=models.UniqueConstraint(fields=('sample', 'name'), name='unique_sample_additional_name'),
        ),
        migrations.AddConstraint(
            model_name='samplematerial',
            constraint=models.UniqueConstraint(fields=('sample', 'material_type'), name='unique_sample_material_type'),
        ),
    ]
