# Generated by Django 5.0.6 on 2025-05-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesar_api', '0010_unique_sample_material_additional_name_related_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.country'),
        ),
        migrations.AddField(
            model_name='sample',
            name='last_registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_last_registrant_set', to='sesar_api.sesaruser'),
        ),
        migrations.AddField(
            model_name='sample',
            name='req_registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_req_registrant_set', to='sesar_api.sesaruser'),
        ),
        migrations.AddField(
            model_name='sesaruser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sesar_api.country'),
        ),
    ]
