# Generated by Django 5.1.6 on 2025-02-21 19:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualStats',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('batches_processed', models.IntegerField(blank=True, null=True)),
                ('new_users', models.IntegerField(blank=True, null=True)),
                ('active_users', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annual_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(max_length=10)),
                ('user_code', models.CharField(max_length=10)),
                ('sample_count', models.IntegerField(blank=True, null=True)),
                ('upload_time', models.DateTimeField()),
                ('processed_time', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=64, null=True)),
                ('deleted_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.TextField()),
                ('download_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'download_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleDeleteRequest',
            fields=[
                ('sample_id', models.IntegerField(blank=True, null=True)),
                ('requestor_user_id', models.IntegerField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('duplicate_igsns', models.CharField(blank=True, max_length=1000, null=True)),
                ('other_reason', models.CharField(blank=True, max_length=250, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('deactivated_by', models.IntegerField(blank=True, null=True)),
                ('deactivated_date', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sample_delete_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleRegistrationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(unique=True)),
                ('samples_registered', models.IntegerField(blank=True, null=True)),
                ('samples_updated', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_registration_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleUploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_from', models.CharField(blank=True, max_length=256, null=True)),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_upload_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AffiliationType',
            fields=[
                ('affiliation_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'affiliation_type',
            },
        ),
        migrations.CreateModel(
            name='AgentRoleType',
            fields=[
                ('agent_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent_role_type',
            },
        ),
        migrations.CreateModel(
            name='CollectionType',
            fields=[
                ('collection_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'collection_type',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('iso3166code', models.CharField(blank=True, max_length=3, null=True)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='GeologicTimeScale',
            fields=[
                ('geologic_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geologic_time_interval_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('numeric_older_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('numeric_younger_bound', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('notation', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'geologic_time_scale',
                'db_table_comment': 'vocabulary of ICS geologic time ordinal eras, 2024 version',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('individual_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('alt_label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'individual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InitiativeType',
            fields=[
                ('initiative_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'initiative_type',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('alt_label', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activate_date', models.DateField(auto_now_add=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, db_comment='email specific to this affiliation; this is the point of contact for the institution', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_comment='location address specific to this affiliation', max_length=500, null=True)),
            ],
            options={
                'db_table': 'institution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('institution_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'institution_type',
            },
        ),
        migrations.CreateModel(
            name='LaunchType',
            fields=[
                ('launch_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'launch_type',
            },
        ),
        migrations.CreateModel(
            name='LocationMethod',
            fields=[
                ('location_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location_method',
                'db_table_comment': 'was nav_type',
            },
        ),
        migrations.CreateModel(
            name='MaterialRoleType',
            fields=[
                ('material_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_role_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_name', models.CharField(blank=True, max_length=50, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'material_role_type',
            },
        ),
        migrations.CreateModel(
            name='PlatformType',
            fields=[
                ('platform_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'platform_type',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('property_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'property_type',
                'db_table_comment': 'vocabulary of properties that might have values assigned for a material sample',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('relation_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'relation_type',
                'db_table_comment': 'terms to assign semantics for relations between samples. Relations can detail the relationship between parent and child samples, use to link to publications, data, other online resources, relate to other samples.',
            },
        ),
        migrations.CreateModel(
            name='SamplingMethod',
            fields=[
                ('collection_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('method_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sampling_method',
            },
        ),
        migrations.CreateModel(
            name='SesarRole',
            fields=[
                ('sesar_role_id', models.AutoField(db_column='sesar_role_id', primary_key=True, serialize=False)),
                ('sesar_role_name', models.CharField(max_length=16)),
                ('sesar_role_description', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'sesar_role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SesarSpatialRefSys',
            fields=[
                ('spatial_ref_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=254, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'sesar_spatial_ref_sys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=255, null=True)),
                ('activate_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('doi_prefix', models.CharField(default='10.58052/', max_length=16)),
                ('part_of_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='newdb.group')),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('affiliation_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activate_date', models.DateField(auto_now_add=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, db_comment='email specific to this affiliation', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_comment='location address specific to this affiliation', max_length=500, null=True)),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.affiliationtype')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='affiliated_individual_id', to='newdb.individual')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.institution')),
            ],
            options={
                'db_table': 'affiliation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('initiative_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('funding', models.CharField(blank=True, max_length=50, null=True)),
                ('begin_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('initiative_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('initiative_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.initiativetype')),
            ],
            options={
                'db_table': 'initiative',
                'db_table_comment': 'Definition of an activity related to sample collection or stewardship. includes cruises, field programs, funded projects, ',
            },
        ),
        migrations.AddField(
            model_name='individual',
            name='affiliation',
            field=models.ManyToManyField(related_name='affiliatedWith_id', through='newdb.Affiliation', to='newdb.institution'),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.institutiontype'),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('locality_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('locality_uri', models.CharField(blank=True, db_comment='use mindat location identifiers?', max_length=512, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('permit', models.CharField(blank=True, max_length=255, null=True)),
                ('collection_policy', models.CharField(blank=True, max_length=1000, null=True)),
                ('contained_in', models.ForeignKey(blank=True, db_column='contained_in', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.locality')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.country')),
            ],
            options={
                'db_table': 'locality',
                'db_table_comment': 'definition of a named place associated with some geologic feature of interest. Binding to concrete geospatial coordinate location is assumed to be through information linked at locality_uri.',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('material_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.materialtype')),
            ],
            options={
                'db_table': 'material_type',
                'db_table_comment': 'was classification',
            },
        ),
        migrations.CreateModel(
            name='ParentInstitution',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activate_date', models.DateField(auto_now_add=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.institution')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_institution_id', to='newdb.institution')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.affiliationtype')),
            ],
            options={
                'db_table': 'parent_institution',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('host_platform_id', models.IntegerField(blank=True, null=True)),
                ('date_commissioned', models.DateField(blank=True, null=True)),
                ('launch_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.launchtype')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.institution')),
                ('platform_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.platformtype')),
            ],
            options={
                'db_table': 'platform',
                'db_table_comment': 'Definition of a facility that hosts sampling activities. Typically a ship or ship-based device (e.g. alvin) used to explore marine water bodies in accessible to direct human occupation.  Extent to include extraterrestrial  exploration devices like OSIRIS-REx. ',
            },
        ),
        migrations.CreateModel(
            name='RelatedSampleAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_agent_id', models.IntegerField(verbose_name=django.db.models.deletion.DO_NOTHING)),
                ('agent_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'Group'), ('INSTITUTION', 'Institution')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activate_date', models.DateField(auto_now_add=True)),
                ('deactivate_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.group')),
                ('individual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.individual')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.institution')),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.agentroletype')),
            ],
            options={
                'db_table': 'related_sample_agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('resource_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('broader_type', models.ForeignKey(blank=True, default='-9999', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.resourcetype')),
            ],
            options={
                'db_table': 'resource_type',
                'db_table_comment': 'kinds of things a sample can be related to, e.g. publication, dataset, sample, research project',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id', models.AutoField(db_comment='primary key for database. ', primary_key=True, serialize=False)),
                ('igsn', models.CharField(db_comment='globally unique identifier string that identifies the material sample. In DataCite/DOI context, this includes the DOI handle, the IGSN prefix and the token assigned when the sample was registered, the toke MUST be unique in the context of the DOI handle and IGSN prefix.', max_length=60)),
                ('igsn_prefix', models.CharField(db_comment='This includes the DOI handle prefix and the IGSN registration authority prefix.  ', max_length=5)),
                ('name', models.CharField(db_comment='name used to represent the sample in user interface; might be IGSN, or a user-defined label for the sample.', max_length=255)),
                ('igsn_is_system_assigned', models.IntegerField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('archive_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('size', models.CharField(blank=True, db_comment='text string  specifying size of sample; should be measured value with units of measure. MIght use mass or length dimensions. ', max_length=255, null=True)),
                ('material_name_verbatim', models.CharField(blank=True, db_comment='material name as provided by the original sample collector or sample registrant.', max_length=255, null=True)),
                ('sample_description', models.TextField(blank=True, db_comment='Description of the sample; provide details-- material type, textures, dimensions, why collected, how collected, information about the sample context, etc. ', null=True)),
                ('purpose', models.CharField(blank=True, db_comment='brief explanation of why sample was collected.', max_length=100, null=True)),
                ('geologic_age_verbatim', models.CharField(blank=True, db_comment='geologic age of the sample as reported by the original collector or registrant. ', max_length=500, null=True)),
                ('numeric_age_min', models.DecimalField(blank=True, db_comment='Younger numeric temporal coordinate for age of sample; if only have a single age, provide it here and leave age_max null. \n\nunits are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. ', decimal_places=4, max_digits=15, null=True)),
                ('numeric_age_max', models.DecimalField(blank=True, db_comment='Older numeric temporal coordinate for age range of sample; if only have a single age, provide leave age_max null. \n\nunits are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. ', decimal_places=4, max_digits=15, null=True)),
                ('numeric_age_unit', models.CharField(blank=True, db_comment='units are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. ', max_length=32, null=True)),
                ('geologic_unit', models.CharField(blank=True, db_comment='name of the geologic unit that contains the sample.', max_length=500, null=True)),
                ('age_qualifier', models.CharField(blank=True, db_comment='qualifier to indicate if age assignment is exact, if there are know uncertainty bounds on numeric age, if age is questionable, etc.', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, db_comment='latitude of point location where sample was collected, reported in decimal degrees using WGS84 Spatial reference system. Location coordinates will be rounded to 6 decimal places.  If the sampling location position is specified with other spatial reference system, link through the location table.', decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, db_comment='longitude of point location where sample was collected, reported in decimal degrees using WGS84 Spatial reference system.  Location coordinates will be rounded to 6 decimal places.   If the sampling location position is specified with other spatial reference system, link through the location table.', decimal_places=6, max_digits=9, null=True)),
                ('latitude_end', models.DecimalField(blank=True, db_comment='If the sampling location is a linear feature (e.g. the track of a dredge haul), report the latitude of the end of the feature, using WGS84 decimal degrees.  ', decimal_places=6, max_digits=8, null=True)),
                ('longitude_end', models.DecimalField(blank=True, db_comment='If the sampling location is a linear feature (e.g. the track of a dredge haul), report the longitude of the end of the feature, using WGS84 decimal degrees. ', decimal_places=6, max_digits=9, null=True)),
                ('geom_latlong', models.TextField(blank=True, null=True)),
                ('depth_min', models.DecimalField(blank=True, db_comment='minimum vertical coordinate below a reference datum,measured positive increasing away from the datum point', decimal_places=4, max_digits=9, null=True)),
                ('depth_max', models.DecimalField(blank=True, db_comment='maximum vertical coordinate below some reference datum,measured positive increasing away from the datum point', decimal_places=4, max_digits=9, null=True)),
                ('depth_uom', models.CharField(blank=True, db_comment='units of measure for depth measurements, {meter, foot, centimeter}', max_length=50, null=True)),
                ('elevation', models.DecimalField(blank=True, db_comment='vertical datum is not specified in the legacy data, assume is mean sea level. If depths are reported differentthan the elevation, assume it is the elevation at the boreholeorigin, otherwise assume it is elevation at the sample location.', decimal_places=4, max_digits=9, null=True)),
                ('elevation_uom', models.CharField(blank=True, db_comment='units of measure for depth measurements, {meter, foot, centimeter}', max_length=50, null=True)),
                ('location_qualifier', models.CharField(blank=True, db_comment='indicate uncertainty, whether locations have be obfuscated intentionally, and notes about elevation datums', max_length=128, null=True)),
                ('locality_detail', models.TextField(blank=True, db_comment='linked locality entity has generalized information about the kind of locality; include details specific to this sampling location here.', null=True)),
                ('collection_method_detail', models.CharField(blank=True, db_comment='text content includes details about specifics of the particular collection event for this sample', max_length=1000, null=True)),
                ('launch_label', models.CharField(blank=True, db_comment='label or identifier for a specify sampling platform deployment from a host platform, e.g launch of Alvin submersible from support ship.', max_length=100, null=True)),
                ('collection_start_date', models.DateTimeField(blank=True, db_comment='date and time of sample acquisition; if the acquisition event is only specfied as a time interval, this is the start of that interval. ', null=True)),
                ('collection_end_date', models.DateTimeField(blank=True, db_comment='If sample acquisition event is specified as a date-time interval, this is the end of that interval. ', null=True)),
                ('collection_date_precision', models.CharField(blank=True, db_comment='indicate time interval that collection time is specified; e.g. minutes, hours, days, weeks, months...', max_length=200, null=True)),
                ('metadata_store_status', models.CharField(db_comment='internal status flag used by SESAR to track metadata management', max_length=25)),
                ('legacy_record', models.JSONField(blank=True, null=True)),
                ('cruise_field_prgrm', models.ForeignKey(blank=True, db_comment='link to description of the cruise, field program, funded project or other activity that is the context for the collection of this sample', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.initiative')),
                ('general_material_type', models.ForeignKey(blank=True, db_comment='material type from iSamples material type vocabulary. Multiple more specific material types are specified through the sample_material correlation table.  ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.materialtype')),
                ('geologic_age_older', models.ForeignKey(blank=True, db_comment='Link to geologic time interval definition for older age possible for sample. If only have a single interval, leave this field null. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_geologic_age_older_set', to='newdb.geologictimescale')),
                ('geologic_age_younger', models.ForeignKey(blank=True, db_comment='Link to geologic time interval definition for younger age possible for sample. If only have a single interval, provide that here and leave age_olde_id null. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.geologictimescale')),
                ('individual_collector', models.ManyToManyField(db_comment='individual acknowledged for collection of the sample. ', related_name='sample_collector_individual_id', through='newdb.RelatedSampleAgent', to='newdb.individual')),
                ('institution_collector', models.ManyToManyField(db_comment='institution acknowledged for collection of the sample. ', related_name='sample_collector_institution_id', through='newdb.RelatedSampleAgent', to='newdb.institution')),
                ('launch_platform', models.ForeignKey(blank=True, db_comment='If sampling was hosted indirectly from the facility identified, by platform_id, this identifies the proximate sampling device or facility hosted by the platform_id.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_launch_platform_set', to='newdb.platform')),
                ('locality', models.ForeignKey(blank=True, db_comment='link to place name description of sampling location, as opposed to a coordinate position. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.locality')),
                ('location_method', models.ForeignKey(blank=True, db_comment='link to description of how the location coordinates have been determined', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.locationmethod')),
                ('parent_sample', models.ForeignKey(blank=True, db_comment='This is the sample.sample_id for the parent sample; to get its IGSN would have to do a sample-sample join on origin_sample_id = sample_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('platform', models.ForeignKey(blank=True, db_comment='Facility that hosted the sampling event. Example of indirect host is remote vehicle from a ship.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.platform')),
            ],
            options={
                'db_table': 'sample',
                'db_table_comment': 'base table with core sample description fields. The contents of this table are a digital representation of a physical, material sample.',
            },
        ),
        migrations.AddField(
            model_name='relatedsampleagent',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_sample_id', to='newdb.sample'),
        ),
        migrations.CreateModel(
            name='RelatedResource',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_label', models.CharField(max_length=100)),
                ('related_resource_uri', models.CharField(max_length=255)),
                ('relation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.relationtype')),
                ('related_resource_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.resourcetype')),
                ('related_sesar_sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relatedsesarsample', to='newdb.sample')),
                ('sample', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'related_resource',
                'db_table_comment': "table to provide links to web-accessible related resource via their URIs. Can be used to provide more explicit relation between a subsample and its parent that simply 'parent', e.g. mineral_separate, soluble_fraction...",
            },
        ),
        migrations.CreateModel(
            name='OtherProperty',
            fields=[
                ('property_value_id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(db_comment='text to display property value in user interface', max_length=50)),
                ('property_value_text', models.CharField(db_comment='property value, serialized as text. the value_data_type is used  to convert to number or treat as URI if appropriated', max_length=256)),
                ('value_data_type', models.CharField(db_comment='data type for property value, if need to cast text as numeric or a URI.', max_length=50)),
                ('provenance', models.CharField(blank=True, db_comment='explanation of how (when, who...) the value was determined', max_length=250, null=True)),
                ('property_type', models.ForeignKey(db_comment='foreign key to property type vocabulary', on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.propertytype')),
                ('sample', models.ForeignKey(db_comment='foreign key to sample table to link property attribution to sample', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'other_property',
                'db_table_comment': 'Optional correlation table to link sample with descriptive properties not explicitly included in this schema. Was sample_customized_metadata',
            },
        ),
        migrations.CreateModel(
            name='SampleAdditionalName',
            fields=[
                ('sample_additional_name_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'sample_additional_name',
                'db_table_comment': 'simple table to link one sample to potentially many different other names by which it is known',
            },
        ),
        migrations.CreateModel(
            name='SampleCollection',
            fields=[
                ('collection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(blank=True, null=True)),
                ('collection_type', models.ForeignKey(blank=True, db_comment='type of collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.collectiontype')),
            ],
            options={
                'db_table': 'sample_collection',
                'db_table_comment': 'Definition of set of samples by some user to associate a set of samples for some purpose.',
            },
        ),
        migrations.CreateModel(
            name='CollectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('collection', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.samplecollection')),
            ],
            options={
                'db_table': 'collection_member',
                'db_table_comment': 'correlation table that associated a sample with a collection. ',
            },
        ),
        migrations.CreateModel(
            name='SampledFeatureType',
            fields=[
                ('feature_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('feature_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_feature_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampledfeaturetype')),
            ],
            options={
                'db_table': 'sampled_feature_type',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sampled_feature_type',
            field=models.ForeignKey(blank=True, db_comment='was primary_location_type. Map to iSamples Sampled feature; this will likely be some geoscience feature. Link to controlled vocabulary.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampledfeaturetype'),
        ),
        migrations.AddField(
            model_name='locality',
            name='feature_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampledfeaturetype'),
        ),
        migrations.CreateModel(
            name='SampleMaterial',
            fields=[
                ('sample_material_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, db_comment='explanation of how material was assigned, use to flag material associations added by curators, text analytics AI etc.', null=True)),
                ('material_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.materialroletype')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.materialtype')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'sample_material',
                'db_table_comment': 'Correlation table to implement many to many relationship between samples and material constituents of the sample.',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_material',
            field=models.ManyToManyField(related_name='related_material_id', through='newdb.SampleMaterial', to='newdb.materialtype'),
        ),
        migrations.CreateModel(
            name='SamplePublicationUrl',
            fields=[
                ('sample_publication_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sample', models.ForeignKey(db_comment='link to sample described by this URL content.', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
            ],
            options={
                'db_table': 'sample_publication_url',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('sample_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample_type_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_name', models.CharField(blank=True, max_length=50, null=True)),
                ('scheme_uri', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_sample_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampletype')),
            ],
            options={
                'db_table': 'sample_type',
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(db_comment='corresponds to iSamples material sample type, use iSamples vocabulary with earth science extensions.', on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sampletype'),
        ),
        migrations.AddField(
            model_name='sample',
            name='collection_method',
            field=models.ForeignKey(blank=True, db_comment='link to generic description of the collection method', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.samplingmethod'),
        ),
        migrations.AddField(
            model_name='sample',
            name='depth_spatial_ref',
            field=models.ForeignKey(blank=True, db_comment='link to description of depth spatial reference system, includingdatum, linear reference geometry (if applicable), units of measure,and positive increasing direction', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesarspatialrefsys'),
        ),
        migrations.CreateModel(
            name='GeospatialLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(db_comment='text to display this location position in user interface. ', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, db_comment='information about the position determination and representation.', null=True)),
                ('vertical', models.DecimalField(blank=True, db_comment='based on vertical_srs, might be elevation (positive up) or depth (positive down).', decimal_places=4, max_digits=10, null=True)),
                ('coordinate_1', models.DecimalField(blank=True, db_comment='coordinate order (what is coordinate_1, coordinate_2) and interpretation must be specified in the spatial_reference_system definition. ', decimal_places=4, max_digits=12, null=True)),
                ('coordinate_2', models.DecimalField(blank=True, db_comment='coordinate order (what is coordinate_1, coordinate_2) and interpretation must be specified in the spatial_reference_system definition. ', decimal_places=4, max_digits=12, null=True)),
                ('spatial_reference_system', models.CharField(blank=True, db_column='spatial_reference_system', max_length=100, null=True)),
                ('wkt_geometry', models.CharField(blank=True, db_column='WKT_geometry', max_length=100, null=True)),
                ('global_grid_cell_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sample', models.ForeignKey(db_comment='link to sample that this position applies to. ', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('vertical_srs', models.ForeignKey(blank=True, db_column='vertical_srs', db_comment='defines units of measure for vertical coordinate, positive up or positive down, and the datum-- that is the surface that has a 0 coordinate value.   If the position is within a borehole, the vertical_srs might be the borehole geometry. ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesarspatialrefsys')),
            ],
            options={
                'db_table': 'geospatial_location',
                'db_table_comment': 'The latitude and longitude in the sample table are required to use WGS84 decimal degrees. This table is optional, use to report coordinate locations with spatial reference different from WGS84, e.g. UTM, local grid coordinates, global grid cell identifiers, etc. ',
            },
        ),
        migrations.CreateModel(
            name='SesarUser',
            fields=[
                ('sesar_user', models.AutoField(db_comment='sesar_user_id is same as individual_id except where an individualhas more than one user id or the SESAR user is a group. SESAR user might also be a group', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_comment='email specific to individual or group in context of this user account', max_length=255, null=True)),
                ('sso_account_id', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_permission_status', models.IntegerField(blank=True, default=0, null=True)),
                ('upload_permission_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('legacy_user_id', models.IntegerField(blank=True, null=True)),
                ('geopass_id', models.CharField(blank=True, max_length=255, null=True)),
                ('orcid', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('doi_prefix', models.CharField(default='10.58052/', max_length=10)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('individual', models.ForeignKey(blank=True, db_comment='a sesar user must map to either an individual or a group', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.individual')),
                ('institution', models.ForeignKey(blank=True, db_comment='a sesar user should be affiliated with some institution', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.institution')),
            ],
            options={
                'db_table': 'sesar_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SampleDoc',
            fields=[
                ('sample_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_image', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=2048)),
                ('path_to_file', models.CharField(max_length=400)),
                ('uploaded_date', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=128, null=True)),
                ('sample', models.ForeignKey(db_comment='link to sample described by this URL content.', default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser')),
            ],
            options={
                'db_table': 'sample_doc',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='samplecollection',
            name='collection_owner',
            field=models.ForeignKey(blank=True, db_column='collection_owner', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cur_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_cur_owner_set', to='newdb.sesaruser'),
        ),
        migrations.AddField(
            model_name='sample',
            name='cur_registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_cur_registrant_set', to='newdb.sesaruser'),
        ),
        migrations.AddField(
            model_name='sample',
            name='last_changed_by',
            field=models.ForeignKey(blank=True, db_comment='link to agent who most recently changed the content of this record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sample_last_changed_by_set', to='newdb.sesaruser'),
        ),
        migrations.CreateModel(
            name='RelatedLocalDoc',
            fields=[
                ('local_doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('primary_image', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('path_to_file', models.CharField(blank=True, max_length=400, null=True)),
                ('uploaded_date', models.DateField(blank=True, null=True)),
                ('sample', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sample')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser')),
            ],
            options={
                'db_table': 'related_local_doc',
                'db_table_comment': 'Table to provide links from sample to document hosted in the file system local to the SESAR server',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='newdb.group')),
                ('sesar_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser')),
            ],
            options={
                'db_table': 'group_member',
                'unique_together': {('group', 'sesar_user')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='newdb.GroupMember', to='newdb.sesaruser'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesaruser'),
        ),
        migrations.CreateModel(
            name='SesarUserCode',
            fields=[
                ('user_code', models.CharField(max_length=5, unique=True)),
                ('is_available', models.IntegerField(blank=True, default=1, null=True)),
                ('igsn_count', models.BigIntegerField(blank=True, null=True)),
                ('is_grandfather_code', models.BooleanField(blank=True, default=False, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doi_prefix', models.CharField(blank=True, default='10.58052/', max_length=16, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_codes', to='newdb.group')),
                ('sesar_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_codes', to='newdb.sesaruser')),
            ],
            options={
                'db_table': 'sesar_user_code',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geopass_id', models.CharField(blank=True, max_length=250, null=True)),
                ('activate_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('orcid_id', models.CharField(blank=True, max_length=19, null=True)),
                ('auth_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.group')),
                ('granted_by_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='granted_permissions', to='newdb.group')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='newdb.group')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='newdb.sample')),
                ('sesar_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newdb.sesarrole')),
                ('sesar_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='permissions', to='newdb.sesaruser')),
                ('user_code', models.ForeignKey(blank=True, db_column='user_code', max_length=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='newdb.sesarusercode', to_field='user_code')),
            ],
            options={
                'db_table': 'permission',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('new_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_received', to='newdb.group')),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_received', to='newdb.sesaruser')),
                ('orig_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_sent', to='newdb.group')),
                ('orig_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_sent', to='newdb.sesaruser')),
                ('transfer_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transfers_created', to='newdb.sesaruser')),
            ],
            options={
                'db_table': 'transfer_history',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('part_of_group__isnull', False)), fields=('name', 'part_of_group'), name='unique_name_group'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('part_of_group__isnull', True)), fields=('name',), name='unique_name_when_no_group'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('geopass_id', 'user_code')},
        ),
    ]
