/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 14-Jun-2024 7:50:13 AM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE agent
(
	agent_id serial NOT NULL,
	label varchar(50) NULL,
	fname varchar(100) NULL,
	lname varchar(100) NULL,
	agent_uri varchar(50) NULL,
	address varchar(2000) NULL,
	organization_affiliation_id integer NULL,
	agent_type varchar(50) NULL,
	point_of_contact varchar(50) NULL,
	parent_organization_id integer NULL
)
;

CREATE TABLE collection_type
(
	collection_type_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	source varchar(50) NULL
)
;

CREATE TABLE country
(
	country_id serial NOT NULL,
	label varchar(255) NULL,
	iso3166code varchar(3) NULL,
	is_active integer NULL
)
;

CREATE TABLE geologic_time_scale
(
	geologic_time_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	geologic_time_interval_uri varchar(50) NULL,
	source varchar(50) NULL,
	scheme_uri varchar(50) NULL,
	numeric_older_bound numeric(18,6) NULL,
	numeric_younger_bound numeric(18,6) NULL
)
;

CREATE TABLE geometry_columns
(
	f_table_catalog varchar(256) NOT NULL,
	f_table_schema varchar(256) NOT NULL,
	f_table_name varchar(256) NOT NULL,
	f_geometry_column varchar(256) NOT NULL,
	coord_dimension integer NOT NULL,
	srid integer NOT NULL,
	type varchar(30) NOT NULL
)
;

CREATE TABLE geospatial_location
(
	location_id serial NOT NULL,
	label varchar(50) NULL,	-- text to display this location position in user interface. 
	description varchar(1000) NULL,	-- information about the position determination and representation.
	sample_id integer NULL,	-- link to sample that this position applies to. 
	vertical numeric(10,4) NULL,	-- based on vertical_srs, might be elevation (positive up) or depth (positive down).
	vertical_srs integer NULL,	-- defines units of measure for vertical coordinate, positive up or positive down, and the datum-- that is the surface that has a 0 coordinate value.   If the position is within a borehole, the vertical_srs might be the borehole geometry. 
	coordinate_1 numeric(12,4) NULL,	-- coordinate order (what is coordinate_1, coordinate_2) and interpretation must be specified in the spatial_reference_system definition. 
	coordinate_2 numeric(12,4) NULL,	-- coordinate order (what is coordinate_1, coordinate_2) and interpretation must be specified in the spatial_reference_system definition. 
	spatial_reference_system integer NULL,
	"WKT_geometry" varchar(100) NULL,
	global_grid_cell_id varchar(50) NULL
)
;

CREATE TABLE group_sample
(
	group_sample_id serial NOT NULL,
	group_id integer NULL,
	sample_id integer NULL
)
;

CREATE TABLE groups
(
	group_id serial NOT NULL,
	name varchar(100) NULL,
	description varchar(1000) NULL,
	group_owner_id integer NULL,
	date_created timestamp without time zone NULL,
	group_type_id integer NULL,	-- type of group such as 'award' or 'user defined'
	is_private boolean NULL
)
;

CREATE TABLE initiative
(
	initiative_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	funding varchar(50) NULL,
	begin_date varchar(50) NULL,
	end_date varchar(50) NULL,
	initiative_uri varchar(50) NULL,
	initiative_type_id integer NULL
)
;

CREATE TABLE initiative_type
(
	initiative_type_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	source varchar(50) NULL
)
;

CREATE TABLE launch_type
(
	launch_type_id serial NOT NULL,
	label varchar(100) NULL,
	description varchar(2000) NULL,
	source varchar(50) NULL
)
;

CREATE TABLE locality
(
	locality_id serial NOT NULL,
	name varchar(50) NULL,
	description varchar(50) NULL,
	feature_type_id integer NULL,
	locality_uri varchar(50) NULL,	-- use mindat location identifiers?
	country_id integer NULL,
	province varchar(255) NULL,
	county varchar(255) NULL,
	city varchar(255) NULL,
	permit varchar(50) NULL,
	collection_policy varchar(50) NULL,
	contained_in integer NULL
)
;

CREATE TABLE location_method
(
	location_method_id serial NOT NULL,
	label varchar(100) NULL,
	description varchar(2000) NULL,
	source varchar(50) NULL
)
;

CREATE TABLE material_type
(
	material_type_id serial NOT NULL,
	label varchar(255) NULL,
	description varchar(2000) NULL,
	material_type_uri varchar(200) NULL,
	parent_material_type_id integer NULL,
	source varchar(50) NULL,
	scheme_uri varchar(50) NULL
)
;

CREATE TABLE other_property
(
	property_value_id integer NOT NULL,
	label varchar(50) NULL,	-- text to display property value in user interface
	sample_id integer NOT NULL,	-- foreign key to sample table to link property attribution to sample
	property_type_id integer NOT NULL,	-- foreign key to property type vocabulary
	property_value_text varchar(256) NOT NULL,	-- property value, serialized as text. the value_data_type is used to convert to number or treat as URI if appropriated
	value_data_type varchar(50) NULL,	-- data type for property value, if need to cast text as numeric or a URI.
	provenance varchar(50) NULL	-- explanation of how (when, who...) the value was determined
)
;

CREATE TABLE platform
(
	platform_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(1000) NULL,
	platform_type_id integer NULL,
	host_platform_id integer NULL,
	launch_type_id integer NULL,
	operator_id integer NULL,
	date_commissioned date NULL
)
;

CREATE TABLE platform_type
(
	platform_type_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	source varchar(50) NULL
)
;

CREATE TABLE property_type
(
	property_type_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	property_uri varchar(50) NULL,
	source varchar(50) NULL,
	scheme_uri varchar(50) NULL
)
;

CREATE TABLE related_local_doc
(
	local_doc_id serial NOT NULL,
	sample_id bigint NULL,
	primary_image integer NULL,
	file_name varchar(255) NULL,
	file_type varchar(50) NULL,
	path_to_file varchar(400) NULL,
	uploaded_by integer NULL,
	uploaded_date date NULL
)
;

CREATE TABLE related_resource
(
	relation_id serial NOT NULL,
	sample_id integer NULL,
	relation_type_id integer NULL,
	relation_label varchar(50) NULL,
	related_resource_uri varchar(50) NULL,
	related_resource_type_id integer NULL
)
;

CREATE TABLE relation_type
(
	relation_type_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	source varchar(50) NULL,
	scheme_uri varchar(50) NULL
)
;

CREATE TABLE resource_type
(
	resource_type_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(1000) NULL,
	resource_type_uri varchar(50) NULL,
	source varchar(50) NULL,
	scheme_uri varchar(50) NULL
)
;

CREATE TABLE sample
(
	sample_id serial NOT NULL,	-- primary key for database. 
	igsn varchar(30) NOT NULL,	-- globally unique identifier string that identifies the material sample. In DataCite/DOI context, this includes the DOI handle, the IGSN prefix and the token assigned when the sample was registered, the toke MUST be unique in the context of the DOI handle and IGSN prefix.
	igsn_prefix varchar(5) NOT NULL,	-- This includes the DOI handle prefix and the IGSN registration authority prefix.  
	name varchar(255) NULL,	-- name used to represent the sample in user interface; might be IGSN, or a user-defined label for the sample.
	parent_sample_id bigint NULL,	-- This is the sample.sample_id for the parent sample; to get its IGSN would have to do a sample-sample join on origin_sample_id = sample_id
	sample_type_id integer NULL,	-- corresponds to iSamples material sample type, use iSamples vocabulary with earth science extensions.
	org_registrant_id integer NULL,
	cur_registrant_id integer NOT NULL,
	req_registrant_id integer NULL,
	igsn_is_system_assigned integer NULL,
	is_private integer NULL,
	publish_date timestamp without time zone NULL,
	archive_date timestamp without time zone NULL,
	registration_date timestamp without time zone NULL,
	last_update_date timestamp without time zone NULL,
	current_archive_id integer NULL,	-- link to agent that currently is the steward of the sample.
	original_archive_id integer NULL,	-- link to first agent that was the steward of the sample, if different from the current steward.
	size varchar(255) NULL,	-- text string  specifying size of sample; should be measured value with units of measure. MIght use mass or length dimensions. 
	general_material_type_id integer NULL,	-- material type from iSamples material type vocabulary. Multiple more specific material types are specified through the sample_material correlation table.  
	material_name_verbatim varchar(255) NULL,	-- material name as provided by the original sample collector or sample registrant.
	sample_description varchar(2000) NULL,	-- Description of the sample; provide details-- material type, textures, dimensions, why collected, how collected, information about the sample context, etc. 
	purpose varchar(100) NULL   DEFAULT NULL,	-- brief explanation of why sample was collected.
	geologic_age_verbatim varchar(500) NULL,	-- geologic age of the sample as reported by the original collector or registrant. 
	numeric_age_min numeric NULL,	-- Younger numeric temporal coordinate for age of sample; if only have a single age, provide it here and leave age_max null.   units are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. 
	numeric_age_max numeric NULL,	-- Older numeric temporal coordinate for age range of sample; if only have a single age, provide leave age_max null.   units are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. 
	numeric_age_unit varchar(255) NULL,	-- units are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. 
	geologic_age_younger_id integer NULL,	-- Link to geologic time interval definition for younger age possible for sample. If only have a single interval, provide that here and leave age_olde_id null. 
	geologic_age_older_id integer NULL,	-- Link to geologic time interval definition for older age possible for sample. If only have a single interval, leave this field null. 
	geologic_unit varchar(500) NULL,	-- name of the geologic unit that contains the sample.
	age_qualifier varchar(50) NULL,	-- qualifier to indicate if age assignment is exact, if there are know uncertainty bounds on numeric age, if age is questionable, etc.
	latitude numeric(8,6) NULL,	-- latitude of point location where sample was collected, reported in decimal degrees using WGS84 Spatial reference system. Location coordinates will be rounded to 6 decimal places.  If the sampling location position is specified with other spatial reference system, link through the location table.
	longitude numeric(9,6) NULL,	-- longitude of point location where sample was collected, reported in decimal degrees using WGS84 Spatial reference system.  Location coordinates will be rounded to 6 decimal places.   If the sampling location position is specified with other spatial reference system, link through the location table.
	latitude_end numeric(8,6) NULL,	-- If the sampling location is a linear feature (e.g. the track of a a dredge haul), report the latitude of the end of the feature, using WGS84 decimal degrees.  
	longitude_end numeric(9,6) NULL,	-- If the sampling location is a linear feature (e.g. the track of a a dredge haul), report the longitude of the end of the feature, using WGS84 decimal degrees. 
	vertical_min numeric(9,4) NULL,	-- vertical coordinate of sampling location position. Units of measure and the reference system are reported in the linked vertical_reference definition.
	vertical_max numeric(9,4) NULL,	-- if sampling location is a linear feature, e.g. a core from a borehole, report the max  coordinate of the sampling location position. Units of measure and the reference system are reported in the linked vertical_reference definition.  Generally, for cores, max coordinate will be the deepest beneath to datum. 
	vertical_reference_id integer NULL,	-- link to definition of vertical reference system; the definition must specify the units of measure, the datum ('0' surface) and the positive direction for coordinate values (up or down)
	location_method_id integer NULL,	-- link to description of how the location coordinates have been determined
	location_qualifier varchar(50) NULL,	-- indicate uncertainty, whether locations have be obfuscated intentionally
	sampled_feature_type_id integer NULL,	-- was primary_location_type. Map to iSamples Sampled feature; this will likely be some geoscience feature. Link to controlled vocabulary.
	locality_id integer NULL,	-- link to place name description of sampling location, as opposed to a coordinate position. 
	locality_detail varchar(2000) NULL,	-- linked locality entity has generalized information about the kind of locality; include details specific to this sampling location here. 
	collection_method_id integer NULL,	-- link to generic description of the collection method
	collection_method_detail varchar(1000) NULL,	-- text content includes details about specifics of the particular collection event for this sample
	cruise_field_prgrm_id integer NULL,	-- link to description of the cruise, field program, funded project or other activity that is the context for the collection of this sample
	collector_id integer NULL,	-- agent acknowledged for collection of the sample. 
	platform_id integer NULL,	-- Identifier for the facility that hosted the sampling event either directly or indirectly. Example of indirect host is launch of remote vehicle from a ship.
	launch_platform_id integer NULL   DEFAULT NULL,	-- If sampling was hosted indirectly from the facility identified, by platform_id, this identifies the proximate sampling device or facility hosted by the platform_id.
	launch_label varchar(100) NULL   DEFAULT NULL,	-- label or identifier for a specify sampling platform deployment from a host platform, e.g launch of Alvin submersible from support ship.
	collection_start_date timestamp with time zone NULL,	-- date and time of sample acquisition; if the acquisition event is only specfied as a time interval, this is the start of that interval. 
	collection_end_date timestamp with time zone NULL,	-- If sample acquisition event is specified as a date-time interval, this is the end of that interval. 
	collection_date_precision varchar(200) NULL,	-- indicate time interval that collection time is specified; e.g. minutes, hours, days, weeks, months...
	metadata_store_status varchar(25) NULL,	-- internal status flag used by SESAR to track metadata management
	orig_owner_id integer NULL,	-- link to agent who was original owner of sample, if different from the current owner.
	cur_owner_id integer NULL,	-- link to current owner of the sample. SESAR uses the owner ID to determine permissions for updating sample records.
	last_changed_by_id integer NULL,	-- link to agent who most recently changed the content of this record.
	last_registrant_id integer NULL	-- link to agent that most recently registered the sample.
)
;

CREATE TABLE sample_additional_identifier
(
	sample_external_identifier_id integer NOT NULL,
	sample_id integer NOT NULL,
	identifier_scheme varchar(50) NOT NULL,
	identifier_value varchar(256) NOT NULL
)
;

CREATE TABLE sample_additional_name
(
	additional_name_id serial NOT NULL,
	sample_id bigint NULL,
	name varchar(255) NULL
)
;

CREATE TABLE sample_material
(
	sample_material_id varchar(50) NOT NULL,
	sample_id integer NULL,
	material_type_id integer NULL,
	label varchar(50) NULL,
	description varchar(50) NULL
)
;

CREATE TABLE sample_type
(
	sample_type_id serial NOT NULL,
	label varchar(255) NULL,
	description varchar(50) NULL,
	sample_type_uri varchar(50) NULL,
	parent_sample_type_id integer NULL,
	scheme_name varchar(50) NULL,
	scheme_uri varchar(50) NULL
)
;

CREATE TABLE sampled_feature_type
(
	feature_type_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	feature_type_uri varchar(50) NULL,
	parent_feature_type_id integer NULL,
	source varchar(50) NULL,
	scheme_uri varchar(50) NULL
)
;

CREATE TABLE sampling_method
(
	collection_method_id serial NOT NULL,
	label varchar(50) NULL,
	description varchar(50) NULL,
	method_uri varchar(50) NULL,
	source varchar(50) NULL,
	scheme_uri varchar(50) NULL
)
;

CREATE TABLE sesar_user
(
	sesar_user_id serial NOT NULL,
	sso_account_id integer NULL,
	is_admin integer NOT NULL   DEFAULT 0,
	note varchar(2000) NULL,
	password varchar(255) NULL,
	upload_permission_status integer NULL,
	upload_permission_date date NULL,
	registration_date timestamp without time zone NULL,
	deactivation_date timestamp without time zone NULL,
	legacy_user_id integer NULL,
	geopass_id varchar(255) NULL
)
;

CREATE TABLE spatial_ref_sys
(
	srid integer NOT NULL,
	auth_name varchar(256) NULL,
	auth_srid integer NULL,
	srtext varchar(2048) NULL,
	proj4text varchar(2048) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE agent ADD CONSTRAINT "PK_agent"
	PRIMARY KEY (agent_id)
;

ALTER TABLE collection_type ADD CONSTRAINT "PK_collection_type"
	PRIMARY KEY (collection_type_id)
;

ALTER TABLE country ADD CONSTRAINT country_pkey
	PRIMARY KEY (country_id)
;

ALTER TABLE geologic_time_scale ADD CONSTRAINT "PK_geologic_time_scale"
	PRIMARY KEY (geologic_time_id)
;

ALTER TABLE geometry_columns ADD CONSTRAINT geometry_columns_pk
	PRIMARY KEY (f_table_catalog,f_table_schema,f_table_name,f_geometry_column)
;

ALTER TABLE geospatial_location ADD CONSTRAINT "PK_geospatial_location"
	PRIMARY KEY (location_id)
;

ALTER TABLE group_sample ADD CONSTRAINT group_sample_pkey
	PRIMARY KEY (group_sample_id)
;

ALTER TABLE groups ADD CONSTRAINT groups_pkey
	PRIMARY KEY (group_id)
;

ALTER TABLE initiative ADD CONSTRAINT "PK_initiative"
	PRIMARY KEY (initiative_id)
;

ALTER TABLE initiative 
  ADD CONSTRAINT unique_label UNIQUE (label)
;

ALTER TABLE initiative_type ADD CONSTRAINT "PK_initiative_type"
	PRIMARY KEY (initiative_type_id)
;

ALTER TABLE launch_type ADD CONSTRAINT launch_type_pkey
	PRIMARY KEY (launch_type_id)
;

ALTER TABLE locality ADD CONSTRAINT "PK_locality"
	PRIMARY KEY (locality_id)
;

ALTER TABLE location_method ADD CONSTRAINT "location_method_PK"
	PRIMARY KEY (location_method_id)
;

ALTER TABLE material_type ADD CONSTRAINT "material_type_id_PK"
	PRIMARY KEY (material_type_id)
;

ALTER TABLE other_property ADD CONSTRAINT other_property_value_pk
	PRIMARY KEY (property_value_id)
;

ALTER TABLE platform ADD CONSTRAINT "PK_platform"
	PRIMARY KEY (platform_id)
;

ALTER TABLE platform_type ADD CONSTRAINT "PK_platform_type"
	PRIMARY KEY (platform_type_id)
;

ALTER TABLE property_type ADD CONSTRAINT "PK_property_type"
	PRIMARY KEY (property_type_id)
;

ALTER TABLE related_local_doc ADD CONSTRAINT sample_doc_pkey
	PRIMARY KEY (local_doc_id)
;

ALTER TABLE related_resource ADD CONSTRAINT "PK_related_resource"
	PRIMARY KEY (relation_id)
;

ALTER TABLE relation_type ADD CONSTRAINT "PK_relation_type"
	PRIMARY KEY (relation_type_id)
;

ALTER TABLE resource_type ADD CONSTRAINT "PK_resource_type"
	PRIMARY KEY (resource_type_id)
;

ALTER TABLE sample ADD CONSTRAINT sample_pkey
	PRIMARY KEY (sample_id)
;

ALTER TABLE sample_additional_identifier ADD CONSTRAINT pksample_external_identifier
	PRIMARY KEY (sample_external_identifier_id)
;

ALTER TABLE sample_additional_name ADD CONSTRAINT sample_additional_name_pkey
	PRIMARY KEY (additional_name_id)
;

ALTER TABLE sample_material ADD CONSTRAINT "PK_sample_material"
	PRIMARY KEY (sample_material_id)
;

ALTER TABLE sample_type ADD CONSTRAINT sample_type_pkey
	PRIMARY KEY (sample_type_id)
;

ALTER TABLE sampled_feature_type ADD CONSTRAINT "PK_sampled_feature_type"
	PRIMARY KEY (feature_type_id)
;

ALTER TABLE sampling_method ADD CONSTRAINT "PK_collection_method"
	PRIMARY KEY (collection_method_id)
;

ALTER TABLE sesar_user ADD CONSTRAINT sesar_user_pkey
	PRIMARY KEY (sesar_user_id)
;

ALTER TABLE spatial_ref_sys ADD CONSTRAINT spatial_ref_sys_pkey
	PRIMARY KEY (srid)
;

/* Create Foreign Key Constraints */

ALTER TABLE agent ADD CONSTRAINT "FK_parent_organization"
	FOREIGN KEY (parent_organization_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE agent ADD CONSTRAINT "FK_person_affiliation"
	FOREIGN KEY (organization_affiliation_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE geospatial_location ADD CONSTRAINT "FK_sample_location"
	FOREIGN KEY (sample_id) REFERENCES public.sample (sample_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE geospatial_location ADD CONSTRAINT "FK_spatial_ref_sys"
	FOREIGN KEY (spatial_reference_system) REFERENCES public.spatial_ref_sys (srid) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE geospatial_location ADD CONSTRAINT "FK_vertical_srs"
	FOREIGN KEY (vertical_srs) REFERENCES public.spatial_ref_sys (srid) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE group_sample ADD CONSTRAINT "FK_group_definition"
	FOREIGN KEY (group_id) REFERENCES public.groups (group_id) ON DELETE Cascade ON UPDATE No Action
;

ALTER TABLE group_sample ADD CONSTRAINT "FK_sample_member"
	FOREIGN KEY (sample_id) REFERENCES public.sample (sample_id) ON DELETE Restrict ON UPDATE No Action
;

ALTER TABLE groups ADD CONSTRAINT "FK_group__type"
	FOREIGN KEY (group_type_id) REFERENCES collection_type (collection_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE groups ADD CONSTRAINT "FK_group_owner"
	FOREIGN KEY (group_owner_id) REFERENCES public.sesar_user (sesar_user_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE initiative ADD CONSTRAINT "FK_initiative_type"
	FOREIGN KEY (initiative_type_id) REFERENCES initiative_type (initiative_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE locality ADD CONSTRAINT "FK_contained_in"
	FOREIGN KEY (contained_in) REFERENCES locality (locality_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE locality ADD CONSTRAINT "FK_feature_type"
	FOREIGN KEY (feature_type_id) REFERENCES sampled_feature_type (feature_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE locality ADD CONSTRAINT "FK_locality_country"
	FOREIGN KEY (country_id) REFERENCES public.country (country_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE material_type ADD CONSTRAINT "FK_parent_material_type"
	FOREIGN KEY (parent_material_type_id) REFERENCES public.material_type (material_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE other_property ADD CONSTRAINT "FK_other_property"
	FOREIGN KEY (sample_id) REFERENCES public.sample (sample_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE other_property ADD CONSTRAINT "FK_property_type"
	FOREIGN KEY (property_type_id) REFERENCES property_type (property_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE platform ADD CONSTRAINT "FK_host_platform"
	FOREIGN KEY (platform_id) REFERENCES platform (platform_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE platform ADD CONSTRAINT "FK_launch_type"
	FOREIGN KEY (launch_type_id) REFERENCES public.launch_type (launch_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE platform ADD CONSTRAINT "FK_platform_type"
	FOREIGN KEY (platform_type_id) REFERENCES platform_type (platform_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE related_local_doc ADD CONSTRAINT "FK_local_doc"
	FOREIGN KEY (sample_id) REFERENCES public.sample (sample_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE related_local_doc ADD CONSTRAINT sample_doc_uploaded_by_fkey
	FOREIGN KEY (uploaded_by) REFERENCES public.sesar_user (sesar_user_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE related_resource ADD CONSTRAINT "FK_related_resource"
	FOREIGN KEY (sample_id) REFERENCES public.sample (sample_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE related_resource ADD CONSTRAINT "FK_related_resource_type"
	FOREIGN KEY (related_resource_type_id) REFERENCES resource_type (resource_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE related_resource ADD CONSTRAINT "FK_relation_type"
	FOREIGN KEY (relation_type_id) REFERENCES relation_type (relation_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_collection_method"
	FOREIGN KEY (collection_method_id) REFERENCES sampling_method (collection_method_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_collector"
	FOREIGN KEY (collector_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_cur_owner"
	FOREIGN KEY (cur_owner_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_cur_registrant"
	FOREIGN KEY (cur_registrant_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_current_archive"
	FOREIGN KEY (current_archive_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_general_material_type"
	FOREIGN KEY (general_material_type_id) REFERENCES public.material_type (material_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_geologic_age_older"
	FOREIGN KEY (geologic_age_older_id) REFERENCES geologic_time_scale (geologic_time_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_geologic_age_younger"
	FOREIGN KEY (geologic_age_younger_id) REFERENCES geologic_time_scale (geologic_time_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_initiative"
	FOREIGN KEY (cruise_field_prgrm_id) REFERENCES initiative (initiative_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_last_changed_by"
	FOREIGN KEY (last_changed_by_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_last_registrant"
	FOREIGN KEY (last_registrant_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_launch_platform"
	FOREIGN KEY (launch_platform_id) REFERENCES platform (platform_id) ON DELETE No Action ON UPDATE No Action
;

/*ALTER TABLE sample ADD CONSTRAINT "FK_location_method"
	FOREIGN KEY () REFERENCES  () ON DELETE No Action ON UPDATE No Action
;*/

ALTER TABLE sample ADD CONSTRAINT "FK_org_registrant"
	FOREIGN KEY (org_registrant_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_orig_owner"
	FOREIGN KEY (orig_owner_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_original_archive"
	FOREIGN KEY (original_archive_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_platform"
	FOREIGN KEY (platform_id) REFERENCES platform (platform_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_req_registrant"
	FOREIGN KEY (req_registrant_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_sample_locality"
	FOREIGN KEY (locality_id) REFERENCES locality (locality_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_sample_parent"
	FOREIGN KEY (parent_sample_id) REFERENCES public.sample (sample_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_sample_type"
	FOREIGN KEY (sample_type_id) REFERENCES public.sample_type (sample_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_sampled_feature_type"
	FOREIGN KEY (sampled_feature_type_id) REFERENCES sampled_feature_type (feature_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample ADD CONSTRAINT "FK_vertical_ref_sys"
	FOREIGN KEY (vertical_reference_id) REFERENCES public.spatial_ref_sys (srid) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample_additional_identifier ADD CONSTRAINT "FK_additional_identifier"
	FOREIGN KEY (sample_id) REFERENCES public.sample (sample_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample_additional_name ADD CONSTRAINT "FK_additional_name"
	FOREIGN KEY (sample_id) REFERENCES public.sample (sample_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample_material ADD CONSTRAINT "FK_material_type"
	FOREIGN KEY (material_type_id) REFERENCES public.material_type (material_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample_material ADD CONSTRAINT "FK_sample_material"
	FOREIGN KEY (sample_id) REFERENCES public.sample (sample_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sample_type ADD CONSTRAINT sample_type_parent_fkey
	FOREIGN KEY (parent_sample_type_id) REFERENCES public.sample_type (sample_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sampled_feature_type ADD CONSTRAINT "FK_feature_type_parent"
	FOREIGN KEY (parent_feature_type_id) REFERENCES sampled_feature_type (feature_type_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sesar_user ADD CONSTRAINT "FK_sesar_user"
	FOREIGN KEY (sesar_user_id) REFERENCES agent (agent_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE agent
	IS 'merge Person and Organization into single table to make linking to agents easier. Most roles are hard typed in this model. Need validation criteria-- 
	- If agent_type is Person, then organization_affiliation, fname, lname is allowed, and parent_organization_id should be null
	- if agent_type is Organization, then organization_affiliation, fname, lname should be null and parent_organization_id is allowed. 
	- point of contact should be an e-mail address.  If possible, should be a repository role that will outlast the tenure of individuals at the repository. 
	- label is the text that will be displayed for the agent in UI.  If person name, affiliation, parent organization changes, this should generate a new agent instance; the agent_uri should be constant, allowing aggregation of the various stages of the agent history.'
;

COMMENT ON TABLE geospatial_location
	IS 'The latitude and longitude in the sample table are required to use WGS84 decimal degrees. This table is optional, use to report coordinate locations with spatial reference different from WGS84, e.g. UTM, local grid coordinates, global grid cell identifiers, etc. '
;

COMMENT ON COLUMN geospatial_location.label
	IS 'text to display this location position in user interface. '
;

COMMENT ON COLUMN geospatial_location.description
	IS 'information about the position determination and representation.'
;

COMMENT ON COLUMN geospatial_location.sample_id
	IS 'link to sample that this position applies to. '
;

COMMENT ON COLUMN geospatial_location.vertical
	IS 'based on vertical_srs, might be elevation (positive up) or depth (positive down).'
;

COMMENT ON COLUMN geospatial_location.vertical_srs
	IS 'defines units of measure for vertical coordinate, positive up or positive down, and the datum-- that is the surface that has a 0 coordinate value.   If the position is within a borehole, the vertical_srs might be the borehole geometry. '
;

COMMENT ON COLUMN geospatial_location.coordinate_1
	IS 'coordinate order (what is coordinate_1, coordinate_2) and interpretation must be specified in the spatial_reference_system definition. '
;

COMMENT ON COLUMN geospatial_location.coordinate_2
	IS 'coordinate order (what is coordinate_1, coordinate_2) and interpretation must be specified in the spatial_reference_system definition. '
;

COMMENT ON TABLE group_sample
	IS 'correlation table that associated a sample with a group or collection. '
;

COMMENT ON TABLE groups
	IS 'Definition of a group or collection defined by some user to associate a set of samples for some purpose.'
;

COMMENT ON COLUMN groups.group_type_id
	IS 'type of group such as ''award'' or ''user defined'''
;

COMMENT ON TABLE initiative
	IS 'Definition of an activity related to sample collection or stewardship. includes cruises, field programs, funded projects, '
;

COMMENT ON TABLE locality
	IS 'definition of a named place associated with some geologic feature of interest. Binding to concrete geospatial coordinate location is assumed to be through information linked at locality_uri.'
;

COMMENT ON COLUMN locality.locality_uri
	IS 'use mindat location identifiers?'
;

COMMENT ON TABLE location_method
	IS 'was nav_type'
;

COMMENT ON TABLE material_type
	IS 'was classification'
;

COMMENT ON TABLE other_property
	IS 'Optional correlation table to link sample with descriptive properties not explicitly included in this schema. Was sample_customized_metadata'
;

COMMENT ON COLUMN other_property.label
	IS 'text to display property value in user interface'
;

COMMENT ON COLUMN other_property.sample_id
	IS 'foreign key to sample table to link property attribution to sample'
;

COMMENT ON COLUMN other_property.property_type_id
	IS 'foreign key to property type vocabulary'
;

COMMENT ON COLUMN other_property.property_value_text
	IS 'property value, serialized as text. the value_data_type is used to convert to number or treat as URI if appropriated'
;

COMMENT ON COLUMN other_property.value_data_type
	IS 'data type for property value, if need to cast text as numeric or a URI.'
;

COMMENT ON COLUMN other_property.provenance
	IS 'explanation of how (when, who...) the value was determined'
;

COMMENT ON TABLE platform
	IS 'Definition of a facility that hosts sampling activities. Typically a ship or ship-based device (e.g. alvin) used to explore marine water bodies in accessible to direct human occupation.  Extent to include extraterrestrial  exploration devices like OSIRIS-REx. '
;

COMMENT ON TABLE property_type
	IS 'vocabulary of properties that might have values assigned for a material sample'
;

COMMENT ON TABLE related_local_doc
	IS 'Table to provide links from sample to document hosted in the file system local to the SESAR server'
;

COMMENT ON TABLE related_resource
	IS 'table to provide links to web-accessible related resource via their URIs. Can be used to provide more explicit relation between a subsample and its parent that simply ''parent'', e.g. mineral_separate, soluble_fraction...'
;

COMMENT ON TABLE relation_type
	IS 'terms to assign semantics for relations between samples. Relations can detail the relationship between parent and child samples, use to link to publications, data, other online resources, relate to other samples.'
;

COMMENT ON TABLE resource_type
	IS 'kinds of things a sample can be related to, e.g. publication, dataset, sample, research project'
;

COMMENT ON TABLE sample
	IS 'base table with core sample description fields. The contents of this table are a digital representation of a physical, material sample. '
;

COMMENT ON COLUMN sample.sample_id
	IS 'primary key for database. '
;

COMMENT ON COLUMN sample.igsn
	IS 'globally unique identifier string that identifies the material sample. In DataCite/DOI context, this includes the DOI handle, the IGSN prefix and the token assigned when the sample was registered, the toke MUST be unique in the context of the DOI handle and IGSN prefix.'
;

COMMENT ON COLUMN sample.igsn_prefix
	IS 'This includes the DOI handle prefix and the IGSN registration authority prefix.  '
;

COMMENT ON COLUMN sample.name
	IS 'name used to represent the sample in user interface; might be IGSN, or a user-defined label for the sample.'
;

COMMENT ON COLUMN sample.parent_sample_id
	IS 'This is the sample.sample_id for the parent sample; to get its IGSN would have to do a sample-sample join on origin_sample_id = sample_id'
;

COMMENT ON COLUMN sample.sample_type_id
	IS 'corresponds to iSamples material sample type, use iSamples vocabulary with earth science extensions.'
;

COMMENT ON COLUMN sample.current_archive_id
	IS 'link to agent that currently is the steward of the sample.'
;

COMMENT ON COLUMN sample.original_archive_id
	IS 'link to first agent that was the steward of the sample, if different from the current steward.'
;

COMMENT ON COLUMN sample.size
	IS 'text string  specifying size of sample; should be measured value with units of measure. MIght use mass or length dimensions. '
;

COMMENT ON COLUMN sample.general_material_type_id
	IS 'material type from iSamples material type vocabulary. Multiple more specific material types are specified through the sample_material correlation table.  '
;

COMMENT ON COLUMN sample.material_name_verbatim
	IS 'material name as provided by the original sample collector or sample registrant.'
;

COMMENT ON COLUMN sample.sample_description
	IS 'Description of the sample; provide details-- material type, textures, dimensions, why collected, how collected, information about the sample context, etc. '
;

COMMENT ON COLUMN sample.purpose
	IS 'brief explanation of why sample was collected.'
;

COMMENT ON COLUMN sample.geologic_age_verbatim
	IS 'geologic age of the sample as reported by the original collector or registrant. '
;

COMMENT ON COLUMN sample.numeric_age_min
	IS 'Younger numeric temporal coordinate for age of sample; if only have a single age, provide it here and leave age_max null. 

units are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. '
;

COMMENT ON COLUMN sample.numeric_age_max
	IS 'Older numeric temporal coordinate for age range of sample; if only have a single age, provide leave age_max null. 

units are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. '
;

COMMENT ON COLUMN sample.numeric_age_unit
	IS 'units are specified in numeric_age_unit field.  If a temporal reference system other than standard geologic time frame (yr, ky, my, measured positive back from 1950 CE), describe the reference system in the sample descriptions. '
;

COMMENT ON COLUMN sample.geologic_age_younger_id
	IS 'Link to geologic time interval definition for younger age possible for sample. If only have a single interval, provide that here and leave age_olde_id null. '
;

COMMENT ON COLUMN sample.geologic_age_older_id
	IS 'Link to geologic time interval definition for older age possible for sample. If only have a single interval, leave this field null. '
;

COMMENT ON COLUMN sample.geologic_unit
	IS 'name of the geologic unit that contains the sample.'
;

COMMENT ON COLUMN sample.age_qualifier
	IS 'qualifier to indicate if age assignment is exact, if there are know uncertainty bounds on numeric age, if age is questionable, etc.'
;

COMMENT ON COLUMN sample.latitude
	IS 'latitude of point location where sample was collected, reported in decimal degrees using WGS84 Spatial reference system. Location coordinates will be rounded to 6 decimal places.  If the sampling location position is specified with other spatial reference system, link through the location table.'
;

COMMENT ON COLUMN sample.longitude
	IS 'longitude of point location where sample was collected, reported in decimal degrees using WGS84 Spatial reference system.  Location coordinates will be rounded to 6 decimal places.   If the sampling location position is specified with other spatial reference system, link through the location table.'
;

COMMENT ON COLUMN sample.latitude_end
	IS 'If the sampling location is a linear feature (e.g. the track of a a dredge haul), report the latitude of the end of the feature, using WGS84 decimal degrees.  '
;

COMMENT ON COLUMN sample.longitude_end
	IS 'If the sampling location is a linear feature (e.g. the track of a a dredge haul), report the longitude of the end of the feature, using WGS84 decimal degrees. '
;

COMMENT ON COLUMN sample.vertical_min
	IS 'vertical coordinate of sampling location position. Units of measure and the reference system are reported in the linked vertical_reference definition.'
;

COMMENT ON COLUMN sample.vertical_max
	IS 'if sampling location is a linear feature, e.g. a core from a borehole, report the max  coordinate of the sampling location position. Units of measure and the reference system are reported in the linked vertical_reference definition.  Generally, for cores, max coordinate will be the deepest beneath to datum. '
;

COMMENT ON COLUMN sample.vertical_reference_id
	IS 'link to definition of vertical reference system; the definition must specify the units of measure, the datum (''0'' surface) and the positive direction for coordinate values (up or down)'
;

COMMENT ON COLUMN sample.location_method_id
	IS 'link to description of how the location coordinates have been determined'
;

COMMENT ON COLUMN sample.location_qualifier
	IS 'indicate uncertainty, whether locations have be obfuscated intentionally'
;

COMMENT ON COLUMN sample.sampled_feature_type_id
	IS 'was primary_location_type. Map to iSamples Sampled feature; this will likely be some geoscience feature. Link to controlled vocabulary.'
;

COMMENT ON COLUMN sample.locality_id
	IS 'link to place name description of sampling location, as opposed to a coordinate position. '
;

COMMENT ON COLUMN sample.locality_detail
	IS 'linked locality entity has generalized information about the kind of locality; include details specific to this sampling location here. '
;

COMMENT ON COLUMN sample.collection_method_id
	IS 'link to generic description of the collection method'
;

COMMENT ON COLUMN sample.collection_method_detail
	IS 'text content includes details about specifics of the particular collection event for this sample'
;

COMMENT ON COLUMN sample.cruise_field_prgrm_id
	IS 'link to description of the cruise, field program, funded project or other activity that is the context for the collection of this sample'
;

COMMENT ON COLUMN sample.collector_id
	IS 'agent acknowledged for collection of the sample. '
;

COMMENT ON COLUMN sample.platform_id
	IS 'Identifier for the facility that hosted the sampling event either directly or indirectly. Example of indirect host is launch of remote vehicle from a ship.'
;

COMMENT ON COLUMN sample.launch_platform_id
	IS 'If sampling was hosted indirectly from the facility identified, by platform_id, this identifies the proximate sampling device or facility hosted by the platform_id.'
;

COMMENT ON COLUMN sample.launch_label
	IS 'label or identifier for a specify sampling platform deployment from a host platform, e.g launch of Alvin submersible from support ship.'
;

COMMENT ON COLUMN sample.collection_start_date
	IS 'date and time of sample acquisition; if the acquisition event is only specfied as a time interval, this is the start of that interval. '
;

COMMENT ON COLUMN sample.collection_end_date
	IS 'If sample acquisition event is specified as a date-time interval, this is the end of that interval. '
;

COMMENT ON COLUMN sample.collection_date_precision
	IS 'indicate time interval that collection time is specified; e.g. minutes, hours, days, weeks, months...'
;

COMMENT ON COLUMN sample.metadata_store_status
	IS 'internal status flag used by SESAR to track metadata management'
;

COMMENT ON COLUMN sample.orig_owner_id
	IS 'link to agent who was original owner of sample, if different from the current owner.'
;

COMMENT ON COLUMN sample.cur_owner_id
	IS 'link to current owner of the sample. SESAR uses the owner ID to determine permissions for updating sample records.'
;

COMMENT ON COLUMN sample.last_changed_by_id
	IS 'link to agent who most recently changed the content of this record.'
;

COMMENT ON COLUMN sample.last_registrant_id
	IS 'link to agent that most recently registered the sample.'
;

COMMENT ON CONSTRAINT "FK_general_material_type" ON sample IS 'use with material type scheme = iSamples Material type'
;

COMMENT ON TABLE sample_additional_identifier
	IS 'Simple link to implement one to many relation from sample id to other identifiers assigned to the sample'
;

COMMENT ON TABLE sample_additional_name
	IS 'simple table to link one sample to potentially many different other names by which it is known'
;

COMMENT ON TABLE sample_material
	IS 'Correlation table to implement many to many relationship between samples and material constituents of the sample.'
;
