name: build_publish_nginx_sidecar
on:
  workflow_dispatch:

jobs:
  build_publish_nginx_sidecar:
    uses: ./.github/workflows/build_publish.yml
    with:
      APPLICATION: sesar2-api-nginx-sidecar
      CONTEXT: nginx
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.SESAR_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SESAR_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.SESAR_AWS_REGION }}
