name: deploy_production_sesar2_api
on:
  workflow_dispatch:
  # change to master push when ready for production deployment
  push:
    branches:
      - "new_api"

jobs:
  build_publish_api:
    uses: ./.github/workflows/build_publish.yml
    with:
      APPLICATION: sesar2-api
      CONTEXT: api2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.SESAR_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SESAR_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.SESAR_AWS_REGION }}
  deploy_ecs_api_production:
    needs: [build_publish_api]
    uses: ./.github/workflows/deploy_ecs.yml
    with:
      APPLICATION: sesar2-api
      ENVIRONMENT: production
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.SESAR_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SESAR_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.SESAR_AWS_REGION }}
  deploy_ecs_api_sandbox:
    needs: [build_publish_api]
    uses: ./.github/workflows/deploy_ecs.yml
    with:
      APPLICATION: sesar2-api
      ENVIRONMENT: sandbox
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.SESAR_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SESAR_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.SESAR_AWS_REGION }}
     